<?xml version="1.0" encoding="utf-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <objectiveNumber>0</objectiveNumber>
  <scenarioType>Ambush</scenarioType>
  <FilePath>C:/Users/Ryanne/Desktop/Convoy/Assets/StreamingAssets/Scenarios/G_H_A_Hitchhiker.sc</FilePath>
  <BiomeType>DesertRoad</BiomeType>
  <CombatEndDialog>1</CombatEndDialog>
  <StartDialog>0</StartDialog>
  <CurrentDialog>0</CurrentDialog>
  <ShowGUI>false</ShowGUI>
  <Dialogs>
    <Dialog>
      <GraphRect>
        <x>74</x>
        <y>191</y>
        <position>
          <x>74</x>
          <y>191</y>
        </position>
        <center>
          <x>149.5</x>
          <y>264.5</y>
        </center>
        <min>
          <x>74</x>
          <y>191</y>
        </min>
        <max>
          <x>225</x>
          <y>338</y>
        </max>
        <width>151</width>
        <height>147</height>
        <size>
          <x>151</x>
          <y>147</y>
        </size>
        <xMin>74</xMin>
        <yMin>191</yMin>
        <xMax>225</xMax>
        <yMax>338</yMax>
      </GraphRect>
      <Name>Start dialog</Name>
      <Text>You come across a lone figure standing by the side of the road, he has his arm outstretched and is holding up a thumb.

Hitchhiking in these parts? Seriously?</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>65</y>
                <position>
                  <x>139</x>
                  <y>65</y>
                </position>
                <center>
                  <x>144</x>
                  <y>70</y>
                </center>
                <min>
                  <x>139</x>
                  <y>65</y>
                </min>
                <max>
                  <x>149</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>65</yMin>
                <xMax>149</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>4</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Stop and talk.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>109</y>
                <position>
                  <x>139</x>
                  <y>109</y>
                </position>
                <center>
                  <x>144</x>
                  <y>114</y>
                </center>
                <min>
                  <x>139</x>
                  <y>109</y>
                </min>
                <max>
                  <x>149</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>109</yMin>
                <xMax>149</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>2</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>127</y>
                <position>
                  <x>139</x>
                  <y>127</y>
                </position>
                <center>
                  <x>144</x>
                  <y>132</y>
                </center>
                <min>
                  <x>139</x>
                  <y>127</y>
                </min>
                <max>
                  <x>149</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>127</yMin>
                <xMax>149</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>9</Chance>
              <ToDialog>3</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Keep going.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>80</x>
        <y>537</y>
        <position>
          <x>80</x>
          <y>537</y>
        </position>
        <center>
          <x>155</x>
          <y>587</y>
        </center>
        <min>
          <x>80</x>
          <y>537</y>
        </min>
        <max>
          <x>230</x>
          <y>637</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>80</xMin>
        <yMin>537</yMin>
        <xMax>230</xMax>
        <yMax>637</yMax>
      </GraphRect>
      <Name>Loot dialog</Name>
      <Text>[0loot]</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Take loot</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>458</x>
        <y>470</y>
        <position>
          <x>458</x>
          <y>470</y>
        </position>
        <center>
          <x>536.5</x>
          <y>520</y>
        </center>
        <min>
          <x>458</x>
          <y>470</y>
        </min>
        <max>
          <x>615</x>
          <y>570</y>
        </max>
        <width>157</width>
        <height>100</height>
        <size>
          <x>157</x>
          <y>100</y>
        </size>
        <xMin>458</xMin>
        <yMin>470</yMin>
        <xMax>615</xMax>
        <yMax>570</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>If it had rained more often around here, you probably would've splashed the hitchhiker with a puddle.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Onwards!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>455</x>
        <y>607</y>
        <position>
          <x>455</x>
          <y>607</y>
        </position>
        <center>
          <x>533.5</x>
          <y>657</y>
        </center>
        <min>
          <x>455</x>
          <y>607</y>
        </min>
        <max>
          <x>612</x>
          <y>707</y>
        </max>
        <width>157</width>
        <height>100</height>
        <size>
          <x>157</x>
          <y>100</y>
        </size>
        <xMin>455</xMin>
        <yMin>607</yMin>
        <xMax>612</xMax>
        <yMax>707</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>You leave the hitchhiker behind you. Folks around these parts can't be trusted.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Onwards!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>435</x>
        <y>197</y>
        <position>
          <x>435</x>
          <y>197</y>
        </position>
        <center>
          <x>530</x>
          <y>292.5</y>
        </center>
        <min>
          <x>435</x>
          <y>197</y>
        </min>
        <max>
          <x>625</x>
          <y>388</y>
        </max>
        <width>190</width>
        <height>191</height>
        <size>
          <x>190</x>
          <y>191</y>
        </size>
        <xMin>435</xMin>
        <yMin>197</yMin>
        <xMax>625</xMax>
        <yMax>388</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The man explains he is free-minded spirit, soul-searching whilst travelling Omek Prime.

He tells you his next destination isn't too far from here, and asks for a ride.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddSideObjective">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>178</x>
                <y>83</y>
                <position>
                  <x>178</x>
                  <y>83</y>
                </position>
                <center>
                  <x>183</x>
                  <y>88</y>
                </center>
                <min>
                  <x>178</x>
                  <y>83</y>
                </min>
                <max>
                  <x>188</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>178</xMin>
                <yMin>83</yMin>
                <xMax>188</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>2</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>G_U_Hitchhiker</nodeName>
              <objective>
                <nodeIndex>0</nodeIndex>
                <name>Hitchin' a Ride</name>
                <discription>You picked up a hitchiker, this seems to be his next destination.</discription>
                <number>29</number>
                <nodes>
                  <ObjectiveNode>
                    <nodeDiscription />
                    <location>
                      <x>0</x>
                      <y>0</y>
                    </location>
                    <scenarioName />
                  </ObjectiveNode>
                </nodes>
                <state>Start</state>
              </objective>
              <pos>Random</pos>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>Very well, hop on.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>178</x>
                <y>109</y>
                <position>
                  <x>178</x>
                  <y>109</y>
                </position>
                <center>
                  <x>183</x>
                  <y>114</y>
                </center>
                <min>
                  <x>178</x>
                  <y>109</y>
                </min>
                <max>
                  <x>188</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>178</xMin>
                <yMin>109</yMin>
                <xMax>188</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>6</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>178</x>
                <y>127</y>
                <position>
                  <x>178</x>
                  <y>127</y>
                </position>
                <center>
                  <x>183</x>
                  <y>132</y>
                </center>
                <min>
                  <x>178</x>
                  <y>127</y>
                </min>
                <max>
                  <x>188</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>178</xMin>
                <yMin>127</yMin>
                <xMax>188</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>2</Chance>
              <ToDialog>7</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Shoot him in the head.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>178</x>
                <y>171</y>
                <position>
                  <x>178</x>
                  <y>171</y>
                </position>
                <center>
                  <x>183</x>
                  <y>176</y>
                </center>
                <min>
                  <x>178</x>
                  <y>171</y>
                </min>
                <max>
                  <x>188</x>
                  <y>181</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>178</xMin>
                <yMin>171</yMin>
                <xMax>188</xMax>
                <yMax>181</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>5</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>No can't do, good luck.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>755</x>
        <y>452</y>
        <position>
          <x>755</x>
          <y>452</y>
        </position>
        <center>
          <x>833.5</x>
          <y>502</y>
        </center>
        <min>
          <x>755</x>
          <y>452</y>
        </min>
        <max>
          <x>912</x>
          <y>552</y>
        </max>
        <width>157</width>
        <height>100</height>
        <size>
          <x>157</x>
          <y>100</y>
        </size>
        <xMin>755</xMin>
        <yMin>452</yMin>
        <xMax>912</xMax>
        <yMax>552</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The man curses you for your narrow-mindedness as you leave him standing.

</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Whatever...</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>775</x>
        <y>180</y>
        <position>
          <x>775</x>
          <y>180</y>
        </position>
        <center>
          <x>853.5</x>
          <y>230</y>
        </center>
        <min>
          <x>775</x>
          <y>180</y>
        </min>
        <max>
          <x>932</x>
          <y>280</y>
        </max>
        <width>157</width>
        <height>100</height>
        <size>
          <x>157</x>
          <y>100</y>
        </size>
        <xMin>775</xMin>
        <yMin>180</yMin>
        <xMax>932</xMax>
        <yMax>280</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>All that's left of him is a bloody mess.

Death to all hitchhikers!</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Hate them...</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>757</x>
        <y>295</y>
        <position>
          <x>757</x>
          <y>295</y>
        </position>
        <center>
          <x>849.5</x>
          <y>359.5</y>
        </center>
        <min>
          <x>757</x>
          <y>295</y>
        </min>
        <max>
          <x>942</x>
          <y>424</y>
        </max>
        <width>185</width>
        <height>129</height>
        <size>
          <x>185</x>
          <y>129</y>
        </size>
        <xMin>757</xMin>
        <yMin>295</yMin>
        <xMax>942</xMax>
        <yMax>424</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>As you blast his head off and his body drops to the ground, you notice a [0items] that falls to the ground.

You wonder why one such as him would carry a [0items] around, but oh well. He won't be needing it anymore.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddRandomItem">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>173</x>
                <y>65</y>
                <position>
                  <x>173</x>
                  <y>65</y>
                </position>
                <center>
                  <x>178</x>
                  <y>70</y>
                </center>
                <min>
                  <x>173</x>
                  <y>65</y>
                </min>
                <max>
                  <x>183</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>173</xMin>
                <yMin>65</yMin>
                <xMax>183</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>1</Amount>
            </ButtonAction>
          </Actions>
          <Name>Take it.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Leave it.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
  </Dialogs>
  <Name>G_H_A_Hitchhiker</Name>
</Scenario>