<?xml version="1.0" encoding="utf-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <objectiveNumber>0</objectiveNumber>
  <scenarioType>Ambush</scenarioType>
  <FilePath>C:/Program Files (x86)/Unity/Convoy/Assets/StreamingAssets/Scenarios/P_D_A_Ambush4.sc</FilePath>
  <BiomeType>Road</BiomeType>
  <CombatEndDialog>1</CombatEndDialog>
  <StartDialog>0</StartDialog>
  <CurrentDialog>0</CurrentDialog>
  <ShowGUI>false</ShowGUI>
  <Dialogs>
    <Dialog>
      <GraphRect>
        <x>297</x>
        <y>459</y>
        <position>
          <x>297</x>
          <y>459</y>
        </position>
        <center>
          <x>428.5</x>
          <y>581.5</y>
        </center>
        <min>
          <x>297</x>
          <y>459</y>
        </min>
        <max>
          <x>560</x>
          <y>704</y>
        </max>
        <width>263</width>
        <height>245</height>
        <size>
          <x>263</x>
          <y>245</y>
        </size>
        <xMin>297</xMin>
        <yMin>459</yMin>
        <xMax>560</xMax>
        <yMax>704</yMax>
      </GraphRect>
      <Name>Start dialog</Name>
      <Text>Privateer vehicles are chasing your convoy through this desert.

They are attempting to radio you.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Privateers</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Turn and fight!</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>251</x>
                <y>109</y>
                <position>
                  <x>251</x>
                  <y>109</y>
                </position>
                <center>
                  <x>256</x>
                  <y>114</y>
                </center>
                <min>
                  <x>251</x>
                  <y>109</y>
                </min>
                <max>
                  <x>261</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>251</xMin>
                <yMin>109</yMin>
                <xMax>261</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>4</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>251</x>
                <y>127</y>
                <position>
                  <x>251</x>
                  <y>127</y>
                </position>
                <center>
                  <x>256</x>
                  <y>132</y>
                </center>
                <min>
                  <x>251</x>
                  <y>127</y>
                </min>
                <max>
                  <x>261</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>251</xMin>
                <yMin>127</yMin>
                <xMax>261</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>5</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>251</x>
                <y>145</y>
                <position>
                  <x>251</x>
                  <y>145</y>
                </position>
                <center>
                  <x>256</x>
                  <y>150</y>
                </center>
                <min>
                  <x>251</x>
                  <y>145</y>
                </min>
                <max>
                  <x>261</x>
                  <y>155</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>251</xMin>
                <yMin>145</yMin>
                <xMax>261</xMax>
                <yMax>155</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>6</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>251</x>
                <y>163</y>
                <position>
                  <x>251</x>
                  <y>163</y>
                </position>
                <center>
                  <x>256</x>
                  <y>168</y>
                </center>
                <min>
                  <x>251</x>
                  <y>163</y>
                </min>
                <max>
                  <x>261</x>
                  <y>173</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>251</xMin>
                <yMin>163</yMin>
                <xMax>261</xMax>
                <yMax>173</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>7</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Radio them.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="ModifyJunk">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>251</x>
                <y>207</y>
                <position>
                  <x>251</x>
                  <y>207</y>
                </position>
                <center>
                  <x>256</x>
                  <y>212</y>
                </center>
                <min>
                  <x>251</x>
                  <y>207</y>
                </min>
                <max>
                  <x>261</x>
                  <y>217</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>251</xMin>
                <yMin>207</yMin>
                <xMax>261</xMax>
                <yMax>217</yMax>
              </ButtonRect>
              <Chance>4</Chance>
              <ToDialog>2</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
              <fuelAmount>-5</fuelAmount>
            </ButtonAction>
            <ButtonAction xsi:type="ModifyJunk">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>251</x>
                <y>225</y>
                <position>
                  <x>251</x>
                  <y>225</y>
                </position>
                <center>
                  <x>256</x>
                  <y>230</y>
                </center>
                <min>
                  <x>251</x>
                  <y>225</y>
                </min>
                <max>
                  <x>261</x>
                  <y>235</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>251</xMin>
                <yMin>225</yMin>
                <xMax>261</xMax>
                <yMax>235</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>3</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
              <fuelAmount>-5</fuelAmount>
            </ButtonAction>
          </Actions>
          <Name>Supercharge engines to escape. [#]</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>267</x>
        <y>721</y>
        <position>
          <x>267</x>
          <y>721</y>
        </position>
        <center>
          <x>342</x>
          <y>771</y>
        </center>
        <min>
          <x>267</x>
          <y>721</y>
        </min>
        <max>
          <x>417</x>
          <y>821</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>267</xMin>
        <yMin>721</yMin>
        <xMax>417</xMax>
        <yMax>821</yMax>
      </GraphRect>
      <Name>Loot dialog</Name>
      <Text>[0loot]</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Take loot</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>707</x>
        <y>666</y>
        <position>
          <x>707</x>
          <y>666</y>
        </position>
        <center>
          <x>785.5</x>
          <y>716</y>
        </center>
        <min>
          <x>707</x>
          <y>666</y>
        </min>
        <max>
          <x>864</x>
          <y>766</y>
        </max>
        <width>157</width>
        <height>100</height>
        <size>
          <x>157</x>
          <y>100</y>
        </size>
        <xMin>707</xMin>
        <yMin>666</yMin>
        <xMax>864</xMax>
        <yMax>766</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Your supercharged engines prove sufficient to escape.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Great!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>705</x>
        <y>819</y>
        <position>
          <x>705</x>
          <y>819</y>
        </position>
        <center>
          <x>780</x>
          <y>869</y>
        </center>
        <min>
          <x>705</x>
          <y>819</y>
        </min>
        <max>
          <x>855</x>
          <y>919</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>705</xMin>
        <yMin>819</yMin>
        <xMax>855</xMax>
        <yMax>919</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Despite your supercharged engines, they catch up to you and start firing!</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Privateers</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Defend the MCV!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>813</x>
        <y>79</y>
        <position>
          <x>813</x>
          <y>79</y>
        </position>
        <center>
          <x>907</x>
          <y>142.5</y>
        </center>
        <min>
          <x>813</x>
          <y>79</y>
        </min>
        <max>
          <x>1001</x>
          <y>206</y>
        </max>
        <width>188</width>
        <height>127</height>
        <size>
          <x>188</x>
          <y>127</y>
        </size>
        <xMin>813</xMin>
        <yMin>79</yMin>
        <xMax>1001</xMax>
        <yMax>206</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Yarrrrr.... We demand $40 or we'll take it by force!"</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="ModifyJunk">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>176</x>
                <y>65</y>
                <position>
                  <x>176</x>
                  <y>65</y>
                </position>
                <center>
                  <x>181</x>
                  <y>70</y>
                </center>
                <min>
                  <x>176</x>
                  <y>65</y>
                </min>
                <max>
                  <x>186</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>176</xMin>
                <yMin>65</yMin>
                <xMax>186</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>8</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>-40</Amount>
              <fuelAmount>0</fuelAmount>
            </ButtonAction>
          </Actions>
          <Name>Pay up. [$]</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Privateers</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>You'll have to die trying.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>811</x>
        <y>215</y>
        <position>
          <x>811</x>
          <y>215</y>
        </position>
        <center>
          <x>905</x>
          <y>279.5</y>
        </center>
        <min>
          <x>811</x>
          <y>215</y>
        </min>
        <max>
          <x>999</x>
          <y>344</y>
        </max>
        <width>188</width>
        <height>129</height>
        <size>
          <x>188</x>
          <y>129</y>
        </size>
        <xMin>811</xMin>
        <yMin>215</yMin>
        <xMax>999</xMax>
        <yMax>344</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The privateer vehicles come within firing range and respond:

"Yarrrrr.... We demand $50 or we'll blast you to bits!"</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="ModifyJunk">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>176</x>
                <y>65</y>
                <position>
                  <x>176</x>
                  <y>65</y>
                </position>
                <center>
                  <x>181</x>
                  <y>70</y>
                </center>
                <min>
                  <x>176</x>
                  <y>65</y>
                </min>
                <max>
                  <x>186</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>176</xMin>
                <yMin>65</yMin>
                <xMax>186</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>8</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>-50</Amount>
              <fuelAmount>0</fuelAmount>
            </ButtonAction>
          </Actions>
          <Name>Pay up. [$]</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Privateers</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>You'll have to die trying.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>812</x>
        <y>362</y>
        <position>
          <x>812</x>
          <y>362</y>
        </position>
        <center>
          <x>936</x>
          <y>425.5</y>
        </center>
        <min>
          <x>812</x>
          <y>362</y>
        </min>
        <max>
          <x>1060</x>
          <y>489</y>
        </max>
        <width>248</width>
        <height>127</height>
        <size>
          <x>248</x>
          <y>127</y>
        </size>
        <xMin>812</xMin>
        <yMin>362</yMin>
        <xMax>1060</xMax>
        <yMax>489</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Yarrrrr.... We demand $80 or we'll blast you to bits!"</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="ModifyJunk">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>236</x>
                <y>65</y>
                <position>
                  <x>236</x>
                  <y>65</y>
                </position>
                <center>
                  <x>241</x>
                  <y>70</y>
                </center>
                <min>
                  <x>236</x>
                  <y>65</y>
                </min>
                <max>
                  <x>246</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>236</xMin>
                <yMin>65</yMin>
                <xMax>246</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>8</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>-80</Amount>
              <fuelAmount>0</fuelAmount>
            </ButtonAction>
          </Actions>
          <Name>Pay up. [$]</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Territory</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>You'll have to die trying.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>820</x>
        <y>504</y>
        <position>
          <x>820</x>
          <y>504</y>
        </position>
        <center>
          <x>914</x>
          <y>567.5</y>
        </center>
        <min>
          <x>820</x>
          <y>504</y>
        </min>
        <max>
          <x>1008</x>
          <y>631</y>
        </max>
        <width>188</width>
        <height>127</height>
        <size>
          <x>188</x>
          <y>127</y>
        </size>
        <xMin>820</xMin>
        <yMin>504</yMin>
        <xMax>1008</xMax>
        <yMax>631</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Yarrrrr.... We demand $100 or we'll blast you to bits!"</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="ModifyJunk">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>176</x>
                <y>65</y>
                <position>
                  <x>176</x>
                  <y>65</y>
                </position>
                <center>
                  <x>181</x>
                  <y>70</y>
                </center>
                <min>
                  <x>176</x>
                  <y>65</y>
                </min>
                <max>
                  <x>186</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>176</xMin>
                <yMin>65</yMin>
                <xMax>186</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>8</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>-100</Amount>
              <fuelAmount>0</fuelAmount>
            </ButtonAction>
          </Actions>
          <Name>Pay up. [$]</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Territory</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>You'll have to die trying.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>1235</x>
        <y>271</y>
        <position>
          <x>1235</x>
          <y>271</y>
        </position>
        <center>
          <x>1313.5</x>
          <y>321</y>
        </center>
        <min>
          <x>1235</x>
          <y>271</y>
        </min>
        <max>
          <x>1392</x>
          <y>371</y>
        </max>
        <width>157</width>
        <height>100</height>
        <size>
          <x>157</x>
          <y>100</y>
        </size>
        <xMin>1235</xMin>
        <yMin>271</yMin>
        <xMax>1392</xMax>
        <yMax>371</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Aarrghhh... pleasure doing business with ya!"

They disperse, leaving your MCV alone.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Good.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
  </Dialogs>
  <Name>P_D_A_Ambush4</Name>
</Scenario>