<?xml version="1.0" encoding="utf-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <objectiveNumber>0</objectiveNumber>
  <scenarioType>Ambush</scenarioType>
  <FilePath>C:/Program Files (x86)/Unity/Convoy/Assets/StreamingAssets/Scenarios/R_D_A_Wreck.sc</FilePath>
  <BiomeType>DesertRoad</BiomeType>
  <CombatEndDialog>1</CombatEndDialog>
  <StartDialog>0</StartDialog>
  <CurrentDialog>0</CurrentDialog>
  <ShowGUI>false</ShowGUI>
  <Dialogs>
    <Dialog>
      <GraphRect>
        <x>138</x>
        <y>293</y>
        <position>
          <x>138</x>
          <y>293</y>
        </position>
        <center>
          <x>225</x>
          <y>383.5</y>
        </center>
        <min>
          <x>138</x>
          <y>293</y>
        </min>
        <max>
          <x>312</x>
          <y>474</y>
        </max>
        <width>174</width>
        <height>181</height>
        <size>
          <x>174</x>
          <y>181</y>
        </size>
        <xMin>138</xMin>
        <yMin>293</yMin>
        <xMax>312</xMax>
        <yMax>474</yMax>
      </GraphRect>
      <Name>Start dialog</Name>
      <Text>You spot a battered and broken raider vehicle in the middle of the desert.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>162</x>
                <y>65</y>
                <position>
                  <x>162</x>
                  <y>65</y>
                </position>
                <center>
                  <x>167</x>
                  <y>70</y>
                </center>
                <min>
                  <x>162</x>
                  <y>65</y>
                </min>
                <max>
                  <x>172</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>162</xMin>
                <yMin>65</yMin>
                <xMax>172</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>5</Chance>
              <ToDialog>2</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>162</x>
                <y>83</y>
                <position>
                  <x>162</x>
                  <y>83</y>
                </position>
                <center>
                  <x>167</x>
                  <y>88</y>
                </center>
                <min>
                  <x>162</x>
                  <y>83</y>
                </min>
                <max>
                  <x>172</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>162</xMin>
                <yMin>83</yMin>
                <xMax>172</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>3</Chance>
              <ToDialog>3</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>162</x>
                <y>101</y>
                <position>
                  <x>162</x>
                  <y>101</y>
                </position>
                <center>
                  <x>167</x>
                  <y>106</y>
                </center>
                <min>
                  <x>162</x>
                  <y>101</y>
                </min>
                <max>
                  <x>172</x>
                  <y>111</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>162</xMin>
                <yMin>101</yMin>
                <xMax>172</xMax>
                <yMax>111</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>4</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>162</x>
                <y>119</y>
                <position>
                  <x>162</x>
                  <y>119</y>
                </position>
                <center>
                  <x>167</x>
                  <y>124</y>
                </center>
                <min>
                  <x>162</x>
                  <y>119</y>
                </min>
                <max>
                  <x>172</x>
                  <y>129</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>162</xMin>
                <yMin>119</yMin>
                <xMax>172</xMax>
                <yMax>129</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>5</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Investigate the wreck.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Keep going.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>159</x>
        <y>641</y>
        <position>
          <x>159</x>
          <y>641</y>
        </position>
        <center>
          <x>234</x>
          <y>691</y>
        </center>
        <min>
          <x>159</x>
          <y>641</y>
        </min>
        <max>
          <x>309</x>
          <y>741</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>159</xMin>
        <yMin>641</yMin>
        <xMax>309</xMax>
        <yMax>741</yMax>
      </GraphRect>
      <Name>Loot dialog</Name>
      <Text>[0loot]</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Take loot</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>463</x>
        <y>97</y>
        <position>
          <x>463</x>
          <y>97</y>
        </position>
        <center>
          <x>555.5</x>
          <y>175.5</y>
        </center>
        <min>
          <x>463</x>
          <y>97</y>
        </min>
        <max>
          <x>648</x>
          <y>254</y>
        </max>
        <width>185</width>
        <height>157</height>
        <size>
          <x>185</x>
          <y>157</y>
        </size>
        <xMin>463</xMin>
        <yMin>97</yMin>
        <xMax>648</xMax>
        <yMax>254</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>You strip the vehicle, and manage to obtain:
[0lootn]</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>138</x>
                <y>65</y>
                <position>
                  <x>138</x>
                  <y>65</y>
                </position>
                <center>
                  <x>143</x>
                  <y>70</y>
                </center>
                <min>
                  <x>138</x>
                  <y>65</y>
                </min>
                <max>
                  <x>148</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>138</xMin>
                <yMin>65</yMin>
                <xMax>148</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
            <ButtonAction xsi:type="AddRandomItem">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>173</x>
                <y>83</y>
                <position>
                  <x>173</x>
                  <y>83</y>
                </position>
                <center>
                  <x>178</x>
                  <y>88</y>
                </center>
                <min>
                  <x>173</x>
                  <y>83</y>
                </min>
                <max>
                  <x>183</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>173</xMin>
                <yMin>83</yMin>
                <xMax>183</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>1</Amount>
            </ButtonAction>
            <ButtonAction xsi:type="AddRandomItem">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>173</x>
                <y>101</y>
                <position>
                  <x>173</x>
                  <y>101</y>
                </position>
                <center>
                  <x>178</x>
                  <y>106</y>
                </center>
                <min>
                  <x>173</x>
                  <y>101</y>
                </min>
                <max>
                  <x>183</x>
                  <y>111</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>173</xMin>
                <yMin>101</yMin>
                <xMax>183</xMax>
                <yMax>111</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>2</Amount>
            </ButtonAction>
          </Actions>
          <Name>Great!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>570</x>
        <y>295</y>
        <position>
          <x>570</x>
          <y>295</y>
        </position>
        <center>
          <x>653</x>
          <y>345</y>
        </center>
        <min>
          <x>570</x>
          <y>295</y>
        </min>
        <max>
          <x>736</x>
          <y>395</y>
        </max>
        <width>166</width>
        <height>100</height>
        <size>
          <x>166</x>
          <y>100</y>
        </size>
        <xMin>570</xMin>
        <yMin>295</yMin>
        <xMax>736</xMax>
        <yMax>395</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Sadly, it looks too damaged to be useful.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Oh well, keep going.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>622</x>
        <y>434</y>
        <position>
          <x>622</x>
          <y>434</y>
        </position>
        <center>
          <x>717</x>
          <y>498.5</y>
        </center>
        <min>
          <x>622</x>
          <y>434</y>
        </min>
        <max>
          <x>812</x>
          <y>563</y>
        </max>
        <width>190</width>
        <height>129</height>
        <size>
          <x>190</x>
          <y>129</y>
        </size>
        <xMin>622</xMin>
        <yMin>434</yMin>
        <xMax>812</xMax>
        <yMax>563</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>You find an unusually large amount of bottlecaps in the wreck.

Who knows who's interested in these?</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddSideObjective">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>178</x>
                <y>65</y>
                <position>
                  <x>178</x>
                  <y>65</y>
                </position>
                <center>
                  <x>183</x>
                  <y>70</y>
                </center>
                <min>
                  <x>178</x>
                  <y>65</y>
                </min>
                <max>
                  <x>188</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>178</xMin>
                <yMin>65</yMin>
                <xMax>188</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>P_Bottlecaps</nodeName>
              <objective>
                <nodeIndex>0</nodeIndex>
                <name>Bottlecap Recoverer</name>
                <discription>You found a large number of bottlecaps in an abandoned wreck. Somebody might be interested in these.</discription>
                <number>16</number>
                <nodes>
                  <ObjectiveNode>
                    <nodeDiscription />
                    <location>
                      <x>0</x>
                      <y>0</y>
                    </location>
                    <scenarioName />
                  </ObjectiveNode>
                </nodes>
                <state>Start</state>
              </objective>
              <pos>Random</pos>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>Take them.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Leave them.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>510</x>
        <y>614</y>
        <position>
          <x>510</x>
          <y>614</y>
        </position>
        <center>
          <x>634.5</x>
          <y>678.5</y>
        </center>
        <min>
          <x>510</x>
          <y>614</y>
        </min>
        <max>
          <x>759</x>
          <y>743</y>
        </max>
        <width>249</width>
        <height>129</height>
        <size>
          <x>249</x>
          <y>129</y>
        </size>
        <xMin>510</xMin>
        <yMin>614</yMin>
        <xMax>759</xMax>
        <yMax>743</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>You find a flyer for the Lucky Peacock, the travelling casino.

Since the casino travels around, it can be hard to locate... but this flyer shows the latest coordinates!</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddSideObjective">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>237</x>
                <y>65</y>
                <position>
                  <x>237</x>
                  <y>65</y>
                </position>
                <center>
                  <x>242</x>
                  <y>70</y>
                </center>
                <min>
                  <x>237</x>
                  <y>65</y>
                </min>
                <max>
                  <x>247</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>237</xMin>
                <yMin>65</yMin>
                <xMax>247</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>G_U_Casino</nodeName>
              <objective>
                <nodeIndex>0</nodeIndex>
                <name>Lucky Peacock Casino</name>
                <discription>You found the location of the Lucky Peacock Casino. Head over and try your luck!</discription>
                <number>17</number>
                <nodes>
                  <ObjectiveNode>
                    <nodeDiscription />
                    <location>
                      <x>0</x>
                      <y>0</y>
                    </location>
                    <scenarioName />
                  </ObjectiveNode>
                </nodes>
                <state>Start</state>
              </objective>
              <pos>Random</pos>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>Enter the coordinates to your map.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Not interested.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
  </Dialogs>
  <Name>R_D_A_Wreck</Name>
</Scenario>