<?xml version="1.0" encoding="utf-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <objectiveNumber>0</objectiveNumber>
  <scenarioType>Ambush</scenarioType>
  <FilePath>C:/Program Files (x86)/Unity/Convoy/Assets/StreamingAssets/Scenarios/T_D_A_Ambush2.sc</FilePath>
  <BiomeType>DesertRoad</BiomeType>
  <CombatEndDialog>1</CombatEndDialog>
  <StartDialog>0</StartDialog>
  <CurrentDialog>0</CurrentDialog>
  <ShowGUI>false</ShowGUI>
  <Dialogs>
    <Dialog>
      <GraphRect>
        <x>96</x>
        <y>307</y>
        <position>
          <x>96</x>
          <y>307</y>
        </position>
        <center>
          <x>225</x>
          <y>415.332031</y>
        </center>
        <min>
          <x>96</x>
          <y>307</y>
        </min>
        <max>
          <x>354</x>
          <y>523.664063</y>
        </max>
        <width>258</width>
        <height>216.664063</height>
        <size>
          <x>258</x>
          <y>216.664063</y>
        </size>
        <xMin>96</xMin>
        <yMin>307</yMin>
        <xMax>354</xMax>
        <yMax>523.664063</yMax>
      </GraphRect>
      <Name>Start dialog</Name>
      <Text>From behind some dunes a pack of T.O.R.V.A.K. vehicles approach your convoy, ready to attack!</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Territory</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Prepare to fight!</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>246</x>
                <y>109</y>
                <position>
                  <x>246</x>
                  <y>109</y>
                </position>
                <center>
                  <x>251</x>
                  <y>114</y>
                </center>
                <min>
                  <x>246</x>
                  <y>109</y>
                </min>
                <max>
                  <x>256</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>246</xMin>
                <yMin>109</yMin>
                <xMax>256</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>2</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>246</x>
                <y>127</y>
                <position>
                  <x>246</x>
                  <y>127</y>
                </position>
                <center>
                  <x>251</x>
                  <y>132</y>
                </center>
                <min>
                  <x>246</x>
                  <y>127</y>
                </min>
                <max>
                  <x>256</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>246</xMin>
                <yMin>127</yMin>
                <xMax>256</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>3</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Try to intimidate them to back off.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>246</x>
                <y>171</y>
                <position>
                  <x>246</x>
                  <y>171</y>
                </position>
                <center>
                  <x>251</x>
                  <y>176</y>
                </center>
                <min>
                  <x>246</x>
                  <y>171</y>
                </min>
                <max>
                  <x>256</x>
                  <y>181</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>246</xMin>
                <yMin>171</yMin>
                <xMax>256</xMax>
                <yMax>181</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>4</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>246</x>
                <y>189</y>
                <position>
                  <x>246</x>
                  <y>189</y>
                </position>
                <center>
                  <x>251</x>
                  <y>194</y>
                </center>
                <min>
                  <x>246</x>
                  <y>189</y>
                </min>
                <max>
                  <x>256</x>
                  <y>199</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>246</xMin>
                <yMin>189</yMin>
                <xMax>256</xMax>
                <yMax>199</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>5</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Try to outrun them!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>119</x>
        <y>604</y>
        <position>
          <x>119</x>
          <y>604</y>
        </position>
        <center>
          <x>194</x>
          <y>654</y>
        </center>
        <min>
          <x>119</x>
          <y>604</y>
        </min>
        <max>
          <x>269</x>
          <y>704</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>119</xMin>
        <yMin>604</yMin>
        <xMax>269</xMax>
        <yMax>704</yMax>
      </GraphRect>
      <Name>Loot dialog</Name>
      <Text>[0loot]</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Take loot.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>537</x>
        <y>124</y>
        <position>
          <x>537</x>
          <y>124</y>
        </position>
        <center>
          <x>621.5</x>
          <y>199.699219</y>
        </center>
        <min>
          <x>537</x>
          <y>124</y>
        </min>
        <max>
          <x>706</x>
          <y>275.398438</y>
        </max>
        <width>169</width>
        <height>151.398438</height>
        <size>
          <x>169</x>
          <y>151.398438</y>
        </size>
        <xMin>537</xMin>
        <yMin>124</yMin>
        <xMax>706</xMax>
        <yMax>275.398438</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Evacuate in our moment of triumph. I think you overestimate your chances."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Territory</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Prepare to fight!</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>157</x>
                <y>109</y>
                <position>
                  <x>157</x>
                  <y>109</y>
                </position>
                <center>
                  <x>162</x>
                  <y>114</y>
                </center>
                <min>
                  <x>157</x>
                  <y>109</y>
                </min>
                <max>
                  <x>167</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>157</xMin>
                <yMin>109</yMin>
                <xMax>167</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>4</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>157</x>
                <y>127</y>
                <position>
                  <x>157</x>
                  <y>127</y>
                </position>
                <center>
                  <x>162</x>
                  <y>132</y>
                </center>
                <min>
                  <x>157</x>
                  <y>127</y>
                </min>
                <max>
                  <x>167</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>157</xMin>
                <yMin>127</yMin>
                <xMax>167</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>5</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Try to outrun them!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>599</x>
        <y>294</y>
        <position>
          <x>599</x>
          <y>294</y>
        </position>
        <center>
          <x>700.5</x>
          <y>360.1328</y>
        </center>
        <min>
          <x>599</x>
          <y>294</y>
        </min>
        <max>
          <x>802</x>
          <y>426.265625</y>
        </max>
        <width>203</width>
        <height>132.265625</height>
        <size>
          <x>203</x>
          <y>132.265625</y>
        </size>
        <xMin>599</xMin>
        <yMin>294</yMin>
        <xMax>802</xMax>
        <yMax>426.265625</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"We have overestimated our chances.

We will leave you be."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Good, keep going.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Territory</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>I like those odds, attack!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>893</x>
        <y>250</y>
        <position>
          <x>893</x>
          <y>250</y>
        </position>
        <center>
          <x>974.5</x>
          <y>300</y>
        </center>
        <min>
          <x>893</x>
          <y>250</y>
        </min>
        <max>
          <x>1056</x>
          <y>350</y>
        </max>
        <width>163</width>
        <height>100</height>
        <size>
          <x>163</x>
          <y>100</y>
        </size>
        <xMin>893</xMin>
        <yMin>250</yMin>
        <xMax>1056</xMax>
        <yMax>350</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>You manage to outrun the T.O.R.V.A.K. vehicles, they give up chasing you.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="CloseDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Good.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>882</x>
        <y>457</y>
        <position>
          <x>882</x>
          <y>457</y>
        </position>
        <center>
          <x>989</x>
          <y>507</y>
        </center>
        <min>
          <x>882</x>
          <y>457</y>
        </min>
        <max>
          <x>1096</x>
          <y>557</y>
        </max>
        <width>214</width>
        <height>100</height>
        <size>
          <x>214</x>
          <y>100</y>
        </size>
        <xMin>882</xMin>
        <yMin>457</yMin>
        <xMax>1096</xMax>
        <yMax>557</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>As you attempt to outrun the T.O.R.V.A.K. vehicles, some of them manage to get shots in on your convoy.

One of your vehicles is damaged, but they give up chase eventually.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="DamageRandomCar">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>65</y>
                <position>
                  <x>193</x>
                  <y>65</y>
                </position>
                <center>
                  <x>198</x>
                  <y>70</y>
                </center>
                <min>
                  <x>193</x>
                  <y>65</y>
                </min>
                <max>
                  <x>203</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>65</yMin>
                <xMax>203</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <amount>1</amount>
              <random>false</random>
              <AmountAP>204</AmountAP>
              <AmountHP>108</AmountHP>
            </ButtonAction>
          </Actions>
          <Name>Damn...</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
  </Dialogs>
  <Name>T_D_A_Ambush2</Name>
</Scenario>