<?xml version="1.0" encoding="utf-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <objectiveNumber>0</objectiveNumber>
  <scenarioType>Ambush</scenarioType>
  <FilePath>D:/projects/Convoy/Assets/StreamingAssets/ObjectiveScenarios/Q_Hyperdrive_RaiderStart.sc</FilePath>
  <BiomeType>Road</BiomeType>
  <CombatEndDialog>1</CombatEndDialog>
  <StartDialog>0</StartDialog>
  <CurrentDialog>0</CurrentDialog>
  <ShowGUI>false</ShowGUI>
  <Dialogs>
    <Dialog>
      <GraphRect>
        <x>-740</x>
        <y>220</y>
        <position>
          <x>-740</x>
          <y>220</y>
        </position>
        <center>
          <x>-637.5</x>
          <y>320.5</y>
        </center>
        <min>
          <x>-740</x>
          <y>220</y>
        </min>
        <max>
          <x>-535</x>
          <y>421</y>
        </max>
        <width>205</width>
        <height>201</height>
        <size>
          <x>205</x>
          <y>201</y>
        </size>
        <xMin>-740</xMin>
        <yMin>220</yMin>
        <xMax>-535</xMax>
        <yMax>421</yMax>
      </GraphRect>
      <Name>Start dialog</Name>
      <Text>Vous arrivez au village de Whiteborough, selon Andy, c'était le dernier endroit où l'escouade de raiders a été repéré.

Le fait qu'ils ont été ici est évident au vu du carnage laissé derrière eux.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>65</y>
                <position>
                  <x>193</x>
                  <y>65</y>
                </position>
                <center>
                  <x>198</x>
                  <y>70</y>
                </center>
                <min>
                  <x>193</x>
                  <y>65</y>
                </min>
                <max>
                  <x>203</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>65</yMin>
                <xMax>203</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>3</Chance>
              <ToDialog>2</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>83</y>
                <position>
                  <x>193</x>
                  <y>83</y>
                </position>
                <center>
                  <x>198</x>
                  <y>88</y>
                </center>
                <min>
                  <x>193</x>
                  <y>83</y>
                </min>
                <max>
                  <x>203</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>83</yMin>
                <xMax>203</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>3</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="DamageRandomCar">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>101</y>
                <position>
                  <x>193</x>
                  <y>101</y>
                </position>
                <center>
                  <x>198</x>
                  <y>106</y>
                </center>
                <min>
                  <x>193</x>
                  <y>101</y>
                </min>
                <max>
                  <x>203</x>
                  <y>111</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>101</yMin>
                <xMax>203</xMax>
                <yMax>111</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>4</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <AmountAP>260</AmountAP>
              <AmountHP>230</AmountHP>
            </ButtonAction>
          </Actions>
          <Name>Entrez en ville.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>145</y>
                <position>
                  <x>193</x>
                  <y>145</y>
                </position>
                <center>
                  <x>198</x>
                  <y>150</y>
                </center>
                <min>
                  <x>193</x>
                  <y>145</y>
                </min>
                <max>
                  <x>203</x>
                  <y>155</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>145</yMin>
                <xMax>203</xMax>
                <yMax>155</yMax>
              </ButtonRect>
              <Chance>2</Chance>
              <ToDialog>5</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>163</y>
                <position>
                  <x>193</x>
                  <y>163</y>
                </position>
                <center>
                  <x>198</x>
                  <y>168</y>
                </center>
                <min>
                  <x>193</x>
                  <y>163</y>
                </min>
                <max>
                  <x>203</x>
                  <y>173</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>163</yMin>
                <xMax>203</xMax>
                <yMax>173</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>6</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="DamageRandomCar">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>181</y>
                <position>
                  <x>193</x>
                  <y>181</y>
                </position>
                <center>
                  <x>198</x>
                  <y>186</y>
                </center>
                <min>
                  <x>193</x>
                  <y>181</y>
                </min>
                <max>
                  <x>203</x>
                  <y>191</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>181</yMin>
                <xMax>203</xMax>
                <yMax>191</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>7</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <AmountAP>0</AmountAP>
              <AmountHP>0</AmountHP>
            </ButtonAction>
          </Actions>
          <Name>Scruter les alentours.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-842</x>
        <y>1198</y>
        <position>
          <x>-842</x>
          <y>1198</y>
        </position>
        <center>
          <x>-767</x>
          <y>1258.5</y>
        </center>
        <min>
          <x>-842</x>
          <y>1198</y>
        </min>
        <max>
          <x>-692</x>
          <y>1319</y>
        </max>
        <width>150</width>
        <height>121</height>
        <size>
          <x>150</x>
          <y>121</y>
        </size>
        <xMin>-842</xMin>
        <yMin>1198</yMin>
        <xMax>-692</xMax>
        <yMax>1319</yMax>
      </GraphRect>
      <Name>Loot dialog</Name>
      <Text>Tous les véhicules de raiders ont été détruits.

[0loot]

Espérons que les victimes de Whiteborough pourront à présent profiter de la paix retrouvée.

Andy semble triste.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>138</x>
                <y>65</y>
                <position>
                  <x>138</x>
                  <y>65</y>
                </position>
                <center>
                  <x>143</x>
                  <y>70</y>
                </center>
                <min>
                  <x>138</x>
                  <y>65</y>
                </min>
                <max>
                  <x>148</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>138</xMin>
                <yMin>65</yMin>
                <xMax>148</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>17</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>138</x>
                <y>83</y>
                <position>
                  <x>138</x>
                  <y>83</y>
                </position>
                <center>
                  <x>143</x>
                  <y>88</y>
                </center>
                <min>
                  <x>138</x>
                  <y>83</y>
                </min>
                <max>
                  <x>148</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>138</xMin>
                <yMin>83</yMin>
                <xMax>148</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>18</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>138</x>
                <y>101</y>
                <position>
                  <x>138</x>
                  <y>101</y>
                </position>
                <center>
                  <x>143</x>
                  <y>106</y>
                </center>
                <min>
                  <x>138</x>
                  <y>101</y>
                </min>
                <max>
                  <x>148</x>
                  <y>111</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>138</xMin>
                <yMin>101</yMin>
                <xMax>148</xMax>
                <yMax>111</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>19</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Sommes-nous faits ?</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-81</x>
        <y>42</y>
        <position>
          <x>-81</x>
          <y>42</y>
        </position>
        <center>
          <x>-2.5</x>
          <y>133.5</y>
        </center>
        <min>
          <x>-81</x>
          <y>42</y>
        </min>
        <max>
          <x>76</x>
          <y>225</y>
        </max>
        <width>157</width>
        <height>183</height>
        <size>
          <x>157</x>
          <y>183</y>
        </size>
        <xMin>-81</xMin>
        <yMin>42</yMin>
        <xMax>76</xMax>
        <yMax>225</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Vous remontez la route principale de Whiteborough.

La plupart des bâtiments ont été détruits, des cadavres jonchent les rues et l'air a des odeurs putrides.

Andy fronça les sourcils et murmure: "Putains de bâtards ... ils méritent de payer pour ça."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>145</x>
                <y>65</y>
                <position>
                  <x>145</x>
                  <y>65</y>
                </position>
                <center>
                  <x>150</x>
                  <y>70</y>
                </center>
                <min>
                  <x>145</x>
                  <y>65</y>
                </min>
                <max>
                  <x>155</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>145</xMin>
                <yMin>65</yMin>
                <xMax>155</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>12</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>145</x>
                <y>83</y>
                <position>
                  <x>145</x>
                  <y>83</y>
                </position>
                <center>
                  <x>150</x>
                  <y>88</y>
                </center>
                <min>
                  <x>145</x>
                  <y>83</y>
                </min>
                <max>
                  <x>155</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>145</xMin>
                <yMin>83</yMin>
                <xMax>155</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>16</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>145</x>
                <y>101</y>
                <position>
                  <x>145</x>
                  <y>101</y>
                </position>
                <center>
                  <x>150</x>
                  <y>106</y>
                </center>
                <min>
                  <x>145</x>
                  <y>101</y>
                </min>
                <max>
                  <x>155</x>
                  <y>111</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>145</xMin>
                <yMin>101</yMin>
                <xMax>155</xMax>
                <yMax>111</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>13</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Rechercher des survivants.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>145</x>
                <y>145</y>
                <position>
                  <x>145</x>
                  <y>145</y>
                </position>
                <center>
                  <x>150</x>
                  <y>150</y>
                </center>
                <min>
                  <x>145</x>
                  <y>145</y>
                </min>
                <max>
                  <x>155</x>
                  <y>155</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>145</xMin>
                <yMin>145</yMin>
                <xMax>155</xMax>
                <yMax>155</yMax>
              </ButtonRect>
              <Chance>2</Chance>
              <ToDialog>14</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>145</x>
                <y>163</y>
                <position>
                  <x>145</x>
                  <y>163</y>
                </position>
                <center>
                  <x>150</x>
                  <y>168</y>
                </center>
                <min>
                  <x>145</x>
                  <y>163</y>
                </min>
                <max>
                  <x>155</x>
                  <y>173</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>145</xMin>
                <yMin>163</yMin>
                <xMax>155</xMax>
                <yMax>173</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>15</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Recherches de pistes.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-331</x>
        <y>204</y>
        <position>
          <x>-331</x>
          <y>204</y>
        </position>
        <center>
          <x>-256</x>
          <y>254</y>
        </center>
        <min>
          <x>-331</x>
          <y>204</y>
        </min>
        <max>
          <x>-181</x>
          <y>304</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>-331</xMin>
        <yMin>204</yMin>
        <xMax>-181</xMax>
        <yMax>304</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Lorsque vous vous préparez à conduire sur la route principale, vous êtes soudain entouré de plusieurs véhicules maculés de sang.

Il semblerait que les raiders ne soient jamais partis!

Malgré la surprise, vous parvenez à manœuvrer de telle manière de ne pas être à votre désaventage dans le combat suivant.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Preparez vous au combat!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-337</x>
        <y>317</y>
        <position>
          <x>-337</x>
          <y>317</y>
        </position>
        <center>
          <x>-262</x>
          <y>367</y>
        </center>
        <min>
          <x>-337</x>
          <y>317</y>
        </min>
        <max>
          <x>-187</x>
          <y>417</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>-337</xMin>
        <yMin>317</yMin>
        <xMax>-187</xMax>
        <yMax>417</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Lorsque vous vous préparez à conduire sur la route principale, vous êtes soudain entouré de plusieurs véhicules maculés de sang.

Il semblerait que les raiders ne soient jamais partis!

Ils ouvrent le feu, endommageant un de vos véhicules avant que vous ayez une chance de retraite..</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>1</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Préparez vous au combat!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-333</x>
        <y>468</y>
        <position>
          <x>-333</x>
          <y>468</y>
        </position>
        <center>
          <x>-257.5</x>
          <y>518</y>
        </center>
        <min>
          <x>-333</x>
          <y>468</y>
        </min>
        <max>
          <x>-182</x>
          <y>568</y>
        </max>
        <width>151</width>
        <height>100</height>
        <size>
          <x>151</x>
          <y>100</y>
        </size>
        <xMin>-333</xMin>
        <yMin>468</yMin>
        <xMax>-182</xMax>
        <yMax>568</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Vous ne captez pas les signaux d'autres véhicules.

Les raiders ont du partir depuis longtemps.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>65</y>
                <position>
                  <x>139</x>
                  <y>65</y>
                </position>
                <center>
                  <x>144</x>
                  <y>70</y>
                </center>
                <min>
                  <x>139</x>
                  <y>65</y>
                </min>
                <max>
                  <x>149</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>65</yMin>
                <xMax>149</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>2</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Entrez en ville.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-339</x>
        <y>593</y>
        <position>
          <x>-339</x>
          <y>593</y>
        </position>
        <center>
          <x>-236.5</x>
          <y>675.5</y>
        </center>
        <min>
          <x>-339</x>
          <y>593</y>
        </min>
        <max>
          <x>-134</x>
          <y>758</y>
        </max>
        <width>205</width>
        <height>165</height>
        <size>
          <x>205</x>
          <y>165</y>
        </size>
        <xMin>-339</xMin>
        <yMin>593</yMin>
        <xMax>-134</xMax>
        <yMax>758</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Le scanner récupère les signaux d'un groupe de véhicules quittant cette zone!

Ils pourraient être les raiders que vous recherchez.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>65</y>
                <position>
                  <x>193</x>
                  <y>65</y>
                </position>
                <center>
                  <x>198</x>
                  <y>70</y>
                </center>
                <min>
                  <x>193</x>
                  <y>65</y>
                </min>
                <max>
                  <x>203</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>65</yMin>
                <xMax>203</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>9</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="DamageRandomCar">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>83</y>
                <position>
                  <x>193</x>
                  <y>83</y>
                </position>
                <center>
                  <x>198</x>
                  <y>88</y>
                </center>
                <min>
                  <x>193</x>
                  <y>83</y>
                </min>
                <max>
                  <x>203</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>83</yMin>
                <xMax>203</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>10</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <AmountAP>0</AmountAP>
              <AmountHP>0</AmountHP>
            </ButtonAction>
          </Actions>
          <Name>A leur poursuite!</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>127</y>
                <position>
                  <x>193</x>
                  <y>127</y>
                </position>
                <center>
                  <x>198</x>
                  <y>132</y>
                </center>
                <min>
                  <x>193</x>
                  <y>127</y>
                </min>
                <max>
                  <x>203</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>127</yMin>
                <xMax>203</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>8</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>145</y>
                <position>
                  <x>193</x>
                  <y>145</y>
                </position>
                <center>
                  <x>198</x>
                  <y>150</y>
                </center>
                <min>
                  <x>193</x>
                  <y>145</y>
                </min>
                <max>
                  <x>203</x>
                  <y>155</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>145</yMin>
                <xMax>203</xMax>
                <yMax>155</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>11</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Les contacter par radio.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-353</x>
        <y>809</y>
        <position>
          <x>-353</x>
          <y>809</y>
        </position>
        <center>
          <x>-250.5</x>
          <y>859</y>
        </center>
        <min>
          <x>-353</x>
          <y>809</y>
        </min>
        <max>
          <x>-148</x>
          <y>909</y>
        </max>
        <width>205</width>
        <height>100</height>
        <size>
          <x>205</x>
          <y>100</y>
        </size>
        <xMin>-353</xMin>
        <yMin>809</yMin>
        <xMax>-148</xMax>
        <yMax>909</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Lorsque vous commencez à scanner la zone, vous captez une variété de signaux entourant votre position.

Il semblerait que les raiders soient toujours là, et ils vous attaquent maintenant!</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>1</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Préparez vous au combat!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>1</x>
        <y>617</y>
        <position>
          <x>1</x>
          <y>617</y>
        </position>
        <center>
          <x>76</x>
          <y>667</y>
        </center>
        <min>
          <x>1</x>
          <y>617</y>
        </min>
        <max>
          <x>151</x>
          <y>717</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>1</xMin>
        <yMin>617</yMin>
        <xMax>151</xMax>
        <yMax>717</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Après votre tentative de contact, les véhicules semblent tourner et s'approcher de votre position.

«Nous ne parlons pas avec de la viande, préparez-vous à mourir!

Vous vous interrogez sur le caractère paradoxal de cette déclaration, avant de charger vos armes.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Combat!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>212</x>
        <y>388</y>
        <position>
          <x>212</x>
          <y>388</y>
        </position>
        <center>
          <x>287</x>
          <y>438</y>
        </center>
        <min>
          <x>212</x>
          <y>388</y>
        </min>
        <max>
          <x>362</x>
          <y>488</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>212</xMin>
        <yMin>388</yMin>
        <xMax>362</xMax>
        <yMax>488</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Vous poursuivez les raiders, qui sont facilement rattrappés.

Ils vous font face pour combattre.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Armes prêtes!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>416</x>
        <y>455</y>
        <position>
          <x>416</x>
          <y>455</y>
        </position>
        <center>
          <x>491</x>
          <y>505</y>
        </center>
        <min>
          <x>416</x>
          <y>455</y>
        </min>
        <max>
          <x>566</x>
          <y>555</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>416</xMin>
        <yMin>455</yMin>
        <xMax>566</xMax>
        <yMax>555</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Pendant que vous poursuivez les raiders présumés, votre scanner affiche soudainement beaucoup plus de signaux qui vous entourent!

Il s'avère que les raiders ont servi d'appât pour vous amener droit dans une embuscade, rendant le combat suivant considérablement plus difficile.
</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>2</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Attaquer!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>10</x>
        <y>737</y>
        <position>
          <x>10</x>
          <y>737</y>
        </position>
        <center>
          <x>87.5</x>
          <y>788.5</y>
        </center>
        <min>
          <x>10</x>
          <y>737</y>
        </min>
        <max>
          <x>165</x>
          <y>840</y>
        </max>
        <width>155</width>
        <height>103</height>
        <size>
          <x>155</x>
          <y>103</y>
        </size>
        <xMin>10</xMin>
        <yMin>737</yMin>
        <xMax>165</xMax>
        <yMax>840</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Andy vous arrête, en criant: «Non, ces raiders sont des salauds qui ne méritent pas d'être traités comme des êtres humains.

Il n'y aura pas de conversation, seulement la mort!"</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>143</x>
                <y>65</y>
                <position>
                  <x>143</x>
                  <y>65</y>
                </position>
                <center>
                  <x>148</x>
                  <y>70</y>
                </center>
                <min>
                  <x>143</x>
                  <y>65</y>
                </min>
                <max>
                  <x>153</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>143</xMin>
                <yMin>65</yMin>
                <xMax>153</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>3</Chance>
              <ToDialog>9</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>143</x>
                <y>83</y>
                <position>
                  <x>143</x>
                  <y>83</y>
                </position>
                <center>
                  <x>148</x>
                  <y>88</y>
                </center>
                <min>
                  <x>143</x>
                  <y>83</y>
                </min>
                <max>
                  <x>153</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>143</xMin>
                <yMin>83</yMin>
                <xMax>153</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>10</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Poursuivez les raiders!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>149</x>
        <y>-357</y>
        <position>
          <x>149</x>
          <y>-357</y>
        </position>
        <center>
          <x>246</x>
          <y>-307</y>
        </center>
        <min>
          <x>149</x>
          <y>-357</y>
        </min>
        <max>
          <x>343</x>
          <y>-257</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>149</xMin>
        <yMin>-357</yMin>
        <xMax>343</xMax>
        <yMax>-257</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Vous trouvez un homme gravement blessé, vraisemblablement laissé pour mort.

Malgré les meilleurs efforts de votre équipe médicale, il succombe à ses blessures ... mais pas avant d'avoir balbutié: «Ils sont allés ... à l'est ..."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Hyperdrive_RaiderChase</nodeName>
              <nodeDiscription>Vous avez trouvé un homme mourant à Whiteborough, qui vous a dit la direction des raiders.

Poursuivez-les pour les traduire en justice.</nodeDiscription>
              <pos>Distance</pos>
              <distance>4</distance>
            </ButtonAction>
          </Actions>
          <Name>A leur poursuite!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>196</x>
        <y>-58</y>
        <position>
          <x>196</x>
          <y>-58</y>
        </position>
        <center>
          <x>272</x>
          <y>-6.5</y>
        </center>
        <min>
          <x>196</x>
          <y>-58</y>
        </min>
        <max>
          <x>348</x>
          <y>45</y>
        </max>
        <width>152</width>
        <height>103</height>
        <size>
          <x>152</x>
          <y>103</y>
        </size>
        <xMin>196</xMin>
        <yMin>-58</yMin>
        <xMax>348</xMax>
        <yMax>45</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Malgré tous vos efforts, vous ne trouvez pas de survivants.

Les raiders n'ont laissé personne.
</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>140</x>
                <y>65</y>
                <position>
                  <x>140</x>
                  <y>65</y>
                </position>
                <center>
                  <x>145</x>
                  <y>70</y>
                </center>
                <min>
                  <x>140</x>
                  <y>65</y>
                </min>
                <max>
                  <x>150</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>140</xMin>
                <yMin>65</yMin>
                <xMax>150</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>3</Chance>
              <ToDialog>14</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>140</x>
                <y>83</y>
                <position>
                  <x>140</x>
                  <y>83</y>
                </position>
                <center>
                  <x>145</x>
                  <y>88</y>
                </center>
                <min>
                  <x>140</x>
                  <y>83</y>
                </min>
                <max>
                  <x>150</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>140</xMin>
                <yMin>83</yMin>
                <xMax>150</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>15</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Rechercher des pistes.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>453</x>
        <y>51</y>
        <position>
          <x>453</x>
          <y>51</y>
        </position>
        <center>
          <x>550</x>
          <y>101</y>
        </center>
        <min>
          <x>453</x>
          <y>51</y>
        </min>
        <max>
          <x>647</x>
          <y>151</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>453</xMin>
        <yMin>51</yMin>
        <xMax>647</xMax>
        <yMax>151</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Après avoir considéré les traces laissées derrière eux, la direction que les raiders ont prise semble évidente.

Andy regarde pensif, puis ajoute: "Il ne peuvent pas être loin ... si nous les poursuivons maintenant, nous sommes sûrs de les rattraper."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Hyperdrive_RaiderChase</nodeName>
              <nodeDiscription>Après avoir enquêté sur les traces laissées à Whiteborough, vous avez déterminé que les raiders doivent être autour de cette zone.

Poursuivez-les pour les traduire en justice.</nodeDiscription>
              <pos>Distance</pos>
              <distance>4</distance>
            </ButtonAction>
          </Actions>
          <Name>En route!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>287</x>
        <y>189</y>
        <position>
          <x>287</x>
          <y>189</y>
        </position>
        <center>
          <x>362.5</x>
          <y>240.5</y>
        </center>
        <min>
          <x>287</x>
          <y>189</y>
        </min>
        <max>
          <x>438</x>
          <y>292</y>
        </max>
        <width>151</width>
        <height>103</height>
        <size>
          <x>151</x>
          <y>103</y>
        </size>
        <xMin>287</xMin>
        <yMin>189</yMin>
        <xMax>438</xMax>
        <yMax>292</yMax>
      </GraphRect>
      <Name>Nouveua dialogue</Name>
      <Text>Alors vous vous préparez à chercher des pistes, Andy met sa main sur votre épaule et dit:

«Tenez, entendez-vous ça? Les véhicules ... ils sont tout proche.

Vous apercevez des nuages de poussière au loin.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>65</y>
                <position>
                  <x>139</x>
                  <y>65</y>
                </position>
                <center>
                  <x>144</x>
                  <y>70</y>
                </center>
                <min>
                  <x>139</x>
                  <y>65</y>
                </min>
                <max>
                  <x>149</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>65</yMin>
                <xMax>149</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>3</Chance>
              <ToDialog>9</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>83</y>
                <position>
                  <x>139</x>
                  <y>83</y>
                </position>
                <center>
                  <x>144</x>
                  <y>88</y>
                </center>
                <min>
                  <x>139</x>
                  <y>83</y>
                </min>
                <max>
                  <x>149</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>83</yMin>
                <xMax>149</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>10</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>A leur poursuite!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>180</x>
        <y>-218</y>
        <position>
          <x>180</x>
          <y>-218</y>
        </position>
        <center>
          <x>277</x>
          <y>-168</y>
        </center>
        <min>
          <x>180</x>
          <y>-218</y>
        </min>
        <max>
          <x>374</x>
          <y>-118</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>180</xMin>
        <yMin>-218</yMin>
        <xMax>374</xMax>
        <yMax>-118</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Vous trouvez une femme gravement blessée, vraisemblablement laissée pour mort.

En dépit des meilleurs efforts de votre équipe médicale, elle succombe à ses blessures ... mais pas avant d'avoir balbutié en vous montrant une direction du doigt: "Ils sont allés ... ce ... chemin ..."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Hyperdrive_RaiderChase</nodeName>
              <nodeDiscription>Vous avez trouvé une femme mourante à Whiteborough, qui vous a dit la direction prise par les raiders.

Poursuivez-les pour les traduire en justice.</nodeDiscription>
              <pos>Distance</pos>
              <distance>4</distance>
            </ButtonAction>
          </Actions>
          <Name>A leur poursuite!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-582</x>
        <y>1021</y>
        <position>
          <x>-582</x>
          <y>1021</y>
        </position>
        <center>
          <x>-485</x>
          <y>1071</y>
        </center>
        <min>
          <x>-582</x>
          <y>1021</y>
        </min>
        <max>
          <x>-388</x>
          <y>1121</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>-582</xMin>
        <yMin>1021</yMin>
        <xMax>-388</xMax>
        <yMax>1121</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Malheureusement non, Ô mon frère.

      Il ya une base de privateers dans la région voisine qui m'a échappé jusqu'ici.

      Cela va changer. J'ai reçu un mot d'une petite escouade de privateers en provenance de cette base.

      Nous allons les trouver et nous allons découvrir l'emplacement de leur base"</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Hyperdrive_PrivateerStart2</nodeName>
              <nodeDiscription>Après avoir traduit les raiders responsables de la destruction de Whiteborough en justice, Andy vous a dirigé vers une escouade de privateers.

Poursuivez-les et obtenez l'emplacement de la base des privateers.</nodeDiscription>
              <pos>Distance</pos>
              <distance>9</distance>
            </ButtonAction>
          </Actions>
          <Name>En route.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-497</x>
        <y>1172</y>
        <position>
          <x>-497</x>
          <y>1172</y>
        </position>
        <center>
          <x>-400</x>
          <y>1222</y>
        </center>
        <min>
          <x>-497</x>
          <y>1172</y>
        </min>
        <max>
          <x>-303</x>
          <y>1272</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>-497</xMin>
        <yMin>1172</yMin>
        <xMax>-303</xMax>
        <yMax>1272</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"C'est ce que nous sommes, Ô mon frère.

Bien qu'il y ai toujours plus de justice à rétablir, pour l'instant nos mains sont liées.

Ramenez-moi au bar à lait Sasiak et je vous fournirai votre précieux Hyperdrive Stabilizers."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Hyperdrive_Reward</nodeName>
              <nodeDiscription>Vous avez amené les raiders responsables du massacre de Whiteborough devant la justice.

Andy a promis de vous donner les Stabilisateurs Hyperdrive dès que vous l'aurez ramené au bar à lait Sasiak.</nodeDiscription>
              <pos>SameAs</pos>
              <posSameAs>Q_M_S_Hyperdrive</posSameAs>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>To the milkbar!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-554</x>
        <y>1336</y>
        <position>
          <x>-554</x>
          <y>1336</y>
        </position>
        <center>
          <x>-457</x>
          <y>1386</y>
        </center>
        <min>
          <x>-554</x>
          <y>1336</y>
        </min>
        <max>
          <x>-360</x>
          <y>1436</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>-554</xMin>
        <yMin>1336</yMin>
        <xMax>-360</xMax>
        <yMax>1436</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Malheureusement non, Ô mon frère.

Il y a un poitn de contrôle T.O.R.V.A.K. pas si loin d'ici, qui est supposé effectuer des expériences sur la population locale.

Cela n'a rien de particulièrement suprenant, étant donné que c'est des T.O.R.V.A.K. qu'on parle. Cette fois, c'est personnel.

Ils ont enlevé une de mes relations personnelles."
</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Hyperdrive_TorvakStart2</nodeName>
              <nodeDiscription>Après avoir amené les raiders responsables de la destruction de Whiteborough à la justice, Andy vous a dirigé vers un point de contrôle T.O.R.V.A.K..

Dirigez-vous sur lui et voyez si vous pouvez en découvrir plus sur la relation personnelle d'Andy.</nodeDiscription>
              <pos>Distance</pos>
              <distance>9</distance>
            </ButtonAction>
          </Actions>
          <Name>Let's go!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
  </Dialogs>
  <Name>Q_Hyperdrive_RaiderStart</Name>
</Scenario>
