<?xml version="1.0" encoding="utf-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <objectiveName>Multicellulose Infused Ethanol</objectiveName>
  <objectiveDiscription>You've been told the location of a local chemist running an underground laboratory.

If you seek him out, he might be able to help you synthesize some Multicellulose Infused Ethanol.</objectiveDiscription>
  <objectiveMainDiscription>Your food replicators have been damaged when you crash landed on Omek Prime. Whilst your ship might be operational without them, your crew refuses to fly off without the guarantee of a proper meal every day.

After all, your crew is often quoted stating: "Ask not what you can do for spaceship Mercury, but ask what's for lunch?"

In order to repair them you require Multicellulose Infused Ethanol. After inquiring you've been told that a local chemist runs an underground laboratory, who might be able to synthesize the required Multicellulose Infused Ethanol.</objectiveMainDiscription>
  <objectiveNumber>0</objectiveNumber>
  <scenarioType>Ambush</scenarioType>
  <FilePath>C:/Program Files (x86)/Unity/Convoy/Assets/StreamingAssets/ObjectiveScenarios/Q_M_S_Multi.sc</FilePath>
  <BiomeType>Road</BiomeType>
  <CombatEndDialog>1</CombatEndDialog>
  <StartDialog>0</StartDialog>
  <CurrentDialog>0</CurrentDialog>
  <ShowGUI>false</ShowGUI>
  <Dialogs>
    <Dialog>
      <GraphRect>
        <x>-1505</x>
        <y>600</y>
        <position>
          <x>-1505</x>
          <y>600</y>
        </position>
        <center>
          <x>-1402.5</x>
          <y>664.477539</y>
        </center>
        <min>
          <x>-1505</x>
          <y>600</y>
        </min>
        <max>
          <x>-1300</x>
          <y>728.9551</y>
        </max>
        <width>205</width>
        <height>128.955078</height>
        <size>
          <x>205</x>
          <y>128.955078</y>
        </size>
        <xMin>-1505</xMin>
        <yMin>600</yMin>
        <xMax>-1300</xMax>
        <yMax>728.9551</yMax>
      </GraphRect>
      <Name>Start dialog</Name>
      <Text>You've arrived at the presumed location of the underground laboratory.

All you see is a single shoddy looking shack, which presumably houses the entrance to the underground facility itself.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>65</y>
                <position>
                  <x>193</x>
                  <y>65</y>
                </position>
                <center>
                  <x>198</x>
                  <y>70</y>
                </center>
                <min>
                  <x>193</x>
                  <y>65</y>
                </min>
                <max>
                  <x>203</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>65</yMin>
                <xMax>203</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>3</Chance>
              <ToDialog>2</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="DamageRandomCar">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>83</y>
                <position>
                  <x>193</x>
                  <y>83</y>
                </position>
                <center>
                  <x>198</x>
                  <y>88</y>
                </center>
                <min>
                  <x>193</x>
                  <y>83</y>
                </min>
                <max>
                  <x>203</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>83</yMin>
                <xMax>203</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>3</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <amount>1</amount>
              <random>false</random>
              <AmountAP>0</AmountAP>
              <AmountHP>0</AmountHP>
            </ButtonAction>
          </Actions>
          <Name>Approach the shack.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-1545</x>
        <y>884</y>
        <position>
          <x>-1545</x>
          <y>884</y>
        </position>
        <center>
          <x>-1459.5</x>
          <y>948.5</y>
        </center>
        <min>
          <x>-1545</x>
          <y>884</y>
        </min>
        <max>
          <x>-1374</x>
          <y>1013</y>
        </max>
        <width>171</width>
        <height>129</height>
        <size>
          <x>171</x>
          <y>129</y>
        </size>
        <xMin>-1545</xMin>
        <yMin>884</yMin>
        <xMax>-1374</xMax>
        <yMax>1013</yMax>
      </GraphRect>
      <Name>Loot dialog</Name>
      <Text>You've managed to fight off all the raider vehicles protecting the underground laboratory.

[0loot]

A bald man with a scruffy looking beard emerges from the shack, unfazed by the destroyed vehicles littering the area.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>159</x>
                <y>65</y>
                <position>
                  <x>159</x>
                  <y>65</y>
                </position>
                <center>
                  <x>164</x>
                  <y>70</y>
                </center>
                <min>
                  <x>159</x>
                  <y>65</y>
                </min>
                <max>
                  <x>169</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>159</xMin>
                <yMin>65</yMin>
                <xMax>169</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>5</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Speak to the chemist.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>159</x>
                <y>109</y>
                <position>
                  <x>159</x>
                  <y>109</y>
                </position>
                <center>
                  <x>164</x>
                  <y>114</y>
                </center>
                <min>
                  <x>159</x>
                  <y>109</y>
                </min>
                <max>
                  <x>169</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>159</xMin>
                <yMin>109</yMin>
                <xMax>169</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>4</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Shoot the chemist.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-1211</x>
        <y>379</y>
        <position>
          <x>-1211</x>
          <y>379</y>
        </position>
        <center>
          <x>-1108.5</x>
          <y>482.5</y>
        </center>
        <min>
          <x>-1211</x>
          <y>379</y>
        </min>
        <max>
          <x>-1006</x>
          <y>586</y>
        </max>
        <width>205</width>
        <height>207</height>
        <size>
          <x>205</x>
          <y>207</y>
        </size>
        <xMin>-1211</xMin>
        <yMin>379</yMin>
        <xMax>-1006</xMax>
        <yMax>586</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The shack isn't much bigger than an outhouse, a decrepit looking intercom system is built into the wall next to the door.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>65</y>
                <position>
                  <x>193</x>
                  <y>65</y>
                </position>
                <center>
                  <x>198</x>
                  <y>70</y>
                </center>
                <min>
                  <x>193</x>
                  <y>65</y>
                </min>
                <max>
                  <x>203</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>65</yMin>
                <xMax>203</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>12</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Push the intercom.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>109</y>
                <position>
                  <x>193</x>
                  <y>109</y>
                </position>
                <center>
                  <x>198</x>
                  <y>114</y>
                </center>
                <min>
                  <x>193</x>
                  <y>109</y>
                </min>
                <max>
                  <x>203</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>109</yMin>
                <xMax>203</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>9</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="DamageRandomCar">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>127</y>
                <position>
                  <x>193</x>
                  <y>127</y>
                </position>
                <center>
                  <x>198</x>
                  <y>132</y>
                </center>
                <min>
                  <x>193</x>
                  <y>127</y>
                </min>
                <max>
                  <x>203</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>127</yMin>
                <xMax>203</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>8</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <amount>1</amount>
              <random>false</random>
              <AmountAP>0</AmountAP>
              <AmountHP>0</AmountHP>
            </ButtonAction>
          </Actions>
          <Name>Knock on the door.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>171</y>
                <position>
                  <x>193</x>
                  <y>171</y>
                </position>
                <center>
                  <x>198</x>
                  <y>176</y>
                </center>
                <min>
                  <x>193</x>
                  <y>171</y>
                </min>
                <max>
                  <x>203</x>
                  <y>181</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>171</yMin>
                <xMax>203</xMax>
                <yMax>181</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>10</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>189</y>
                <position>
                  <x>193</x>
                  <y>189</y>
                </position>
                <center>
                  <x>198</x>
                  <y>194</y>
                </center>
                <min>
                  <x>193</x>
                  <y>189</y>
                </min>
                <max>
                  <x>203</x>
                  <y>199</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>189</yMin>
                <xMax>203</xMax>
                <yMax>199</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>11</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Head inside.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-1191</x>
        <y>691</y>
        <position>
          <x>-1191</x>
          <y>691</y>
        </position>
        <center>
          <x>-1116</x>
          <y>741</y>
        </center>
        <min>
          <x>-1191</x>
          <y>691</y>
        </min>
        <max>
          <x>-1041</x>
          <y>791</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>-1191</xMin>
        <yMin>691</yMin>
        <xMax>-1041</xMax>
        <yMax>791</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Evidently the chemist does not welcome visitors, as you are under attack by several raider vehicles!</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Defend yourself!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-1251</x>
        <y>1016</y>
        <position>
          <x>-1251</x>
          <y>1016</y>
        </position>
        <center>
          <x>-1160.5</x>
          <y>1066</y>
        </center>
        <min>
          <x>-1251</x>
          <y>1016</y>
        </min>
        <max>
          <x>-1070</x>
          <y>1116</y>
        </max>
        <width>181</width>
        <height>100</height>
        <size>
          <x>181</x>
          <y>100</y>
        </size>
        <xMin>-1251</xMin>
        <yMin>1016</yMin>
        <xMax>-1070</xMax>
        <yMax>1116</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>After decorating the shack with the insides of the chemist's head, you proceed inside and discover a hatch to the underground laboratory.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>169</x>
                <y>65</y>
                <position>
                  <x>169</x>
                  <y>65</y>
                </position>
                <center>
                  <x>174</x>
                  <y>70</y>
                </center>
                <min>
                  <x>169</x>
                  <y>65</y>
                </min>
                <max>
                  <x>179</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>169</xMin>
                <yMin>65</yMin>
                <xMax>179</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>6</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Explore the laboratory.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-1297</x>
        <y>819</y>
        <position>
          <x>-1297</x>
          <y>819</y>
        </position>
        <center>
          <x>-1148.5</x>
          <y>869</y>
        </center>
        <min>
          <x>-1297</x>
          <y>819</y>
        </min>
        <max>
          <x>-1000</x>
          <y>919</y>
        </max>
        <width>297</width>
        <height>100</height>
        <size>
          <x>297</x>
          <y>100</y>
        </size>
        <xMin>-1297</xMin>
        <yMin>819</yMin>
        <xMax>-1000</xMax>
        <yMax>919</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Looks like my so-called protection wasn't worth the price they demanded.

Thank you for ridding me of their mediocre services.

You're the recent arrivals belonging to the spaceship, I believe? What is it you want of a humble chemist?"</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>285</x>
                <y>65</y>
                <position>
                  <x>285</x>
                  <y>65</y>
                </position>
                <center>
                  <x>290</x>
                  <y>70</y>
                </center>
                <min>
                  <x>285</x>
                  <y>65</y>
                </min>
                <max>
                  <x>295</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>285</xMin>
                <yMin>65</yMin>
                <xMax>295</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>16</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Inquire after Multicellulose Infused Ethanol.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-950</x>
        <y>1006</y>
        <position>
          <x>-950</x>
          <y>1006</y>
        </position>
        <center>
          <x>-874.5</x>
          <y>1056</y>
        </center>
        <min>
          <x>-950</x>
          <y>1006</y>
        </min>
        <max>
          <x>-799</x>
          <y>1106</y>
        </max>
        <width>151</width>
        <height>100</height>
        <size>
          <x>151</x>
          <y>100</y>
        </size>
        <xMin>-950</xMin>
        <yMin>1006</yMin>
        <xMax>-799</xMax>
        <yMax>1106</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Aside from large quantities of narcotics, you discover some research notes regarding Multicellulose Infused Ethanol.

The notes mention that the likeliest source would be a collection of ancient rum. The notes theorize that the barrels in which the rum is stored would've leaked organic matter into the alcohol, which would have synthesized Multicellulose Infused Ethanol.

Whilst that sounds very unlikely by itself, the notes continue by stating that this cargo of ancient rum is carried by a supposed ghosttruck called 'the Driving Dutchman".</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>65</y>
                <position>
                  <x>139</x>
                  <y>65</y>
                </position>
                <center>
                  <x>144</x>
                  <y>70</y>
                </center>
                <min>
                  <x>139</x>
                  <y>65</y>
                </min>
                <max>
                  <x>149</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>65</yMin>
                <xMax>149</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>7</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Keep reading.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-540</x>
        <y>986</y>
        <position>
          <x>-540</x>
          <y>986</y>
        </position>
        <center>
          <x>-443</x>
          <y>1036</y>
        </center>
        <min>
          <x>-540</x>
          <y>986</y>
        </min>
        <max>
          <x>-346</x>
          <y>1086</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>-540</xMin>
        <yMin>986</yMin>
        <xMax>-346</xMax>
        <yMax>1086</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>According to legend, this ghosttruck wanders Omek Prime and serves as an inspiration to all the privateers.

Finally, the notes mention a specific privateer group called "the Silver Earrings" that have last sighted this presumed ghosttruck.

Regardless of how ridiculous this notion sounds, it is the only lead you currently have.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Multi_SilverEar</nodeName>
              <nodeDiscription>In your efforts to acquire Multicellulose Infused Ethanol, your current lead is to seek out a group of privateers who call themselves "the Silver Earrings".

Presumably, they're the last who have sighted the illustrious "Driving Dutchman" which should carry a cargo of ancient rum.</nodeDiscription>
              <pos>Random</pos>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>Great...</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-625</x>
        <y>460</y>
        <position>
          <x>-625</x>
          <y>460</y>
        </position>
        <center>
          <x>-550</x>
          <y>510</y>
        </center>
        <min>
          <x>-625</x>
          <y>460</y>
        </min>
        <max>
          <x>-475</x>
          <y>560</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>-625</xMin>
        <yMin>460</yMin>
        <xMax>-475</xMax>
        <yMax>560</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Moments after knocking on the door, an angry voice emits from the intercom stating: "I AM THE ONE WHO KNOCKS!"

You hear several vehicles approaching your position, so you quickly rush back to your convoy ready to defend yourself from an attack.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Open fire!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-643</x>
        <y>342</y>
        <position>
          <x>-643</x>
          <y>342</y>
        </position>
        <center>
          <x>-567.5</x>
          <y>392</y>
        </center>
        <min>
          <x>-643</x>
          <y>342</y>
        </min>
        <max>
          <x>-492</x>
          <y>442</y>
        </max>
        <width>151</width>
        <height>100</height>
        <size>
          <x>151</x>
          <y>100</y>
        </size>
        <xMin>-643</xMin>
        <yMin>342</yMin>
        <xMax>-492</xMax>
        <yMax>442</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Moments after knocking on the door, a crackling voice emits from the intercom telling you to come inside.

Upon stepping inside, you spot a hatch leading down to the laboratory.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>65</y>
                <position>
                  <x>139</x>
                  <y>65</y>
                </position>
                <center>
                  <x>144</x>
                  <y>70</y>
                </center>
                <min>
                  <x>139</x>
                  <y>65</y>
                </min>
                <max>
                  <x>149</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>65</yMin>
                <xMax>149</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>18</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Enter the hatch.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-921</x>
        <y>349</y>
        <position>
          <x>-921</x>
          <y>349</y>
        </position>
        <center>
          <x>-818.5</x>
          <y>443.5</y>
        </center>
        <min>
          <x>-921</x>
          <y>349</y>
        </min>
        <max>
          <x>-716</x>
          <y>538</y>
        </max>
        <width>205</width>
        <height>189</height>
        <size>
          <x>205</x>
          <y>189</y>
        </size>
        <xMin>-921</xMin>
        <yMin>349</yMin>
        <xMax>-716</xMax>
        <yMax>538</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The door is locked.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>65</y>
                <position>
                  <x>193</x>
                  <y>65</y>
                </position>
                <center>
                  <x>198</x>
                  <y>70</y>
                </center>
                <min>
                  <x>193</x>
                  <y>65</y>
                </min>
                <max>
                  <x>203</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>65</yMin>
                <xMax>203</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>12</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Push the intercom.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>109</y>
                <position>
                  <x>193</x>
                  <y>109</y>
                </position>
                <center>
                  <x>198</x>
                  <y>114</y>
                </center>
                <min>
                  <x>193</x>
                  <y>109</y>
                </min>
                <max>
                  <x>203</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>109</yMin>
                <xMax>203</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>9</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="DamageRandomCar">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>127</y>
                <position>
                  <x>193</x>
                  <y>127</y>
                </position>
                <center>
                  <x>198</x>
                  <y>132</y>
                </center>
                <min>
                  <x>193</x>
                  <y>127</y>
                </min>
                <max>
                  <x>203</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>127</yMin>
                <xMax>203</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>8</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <amount>1</amount>
              <random>false</random>
              <AmountAP>0</AmountAP>
              <AmountHP>0</AmountHP>
            </ButtonAction>
          </Actions>
          <Name>Knock on the door.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>193</x>
                <y>171</y>
                <position>
                  <x>193</x>
                  <y>171</y>
                </position>
                <center>
                  <x>198</x>
                  <y>176</y>
                </center>
                <min>
                  <x>193</x>
                  <y>171</y>
                </min>
                <max>
                  <x>203</x>
                  <y>181</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>193</xMin>
                <yMin>171</yMin>
                <xMax>203</xMax>
                <yMax>181</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>13</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Kick down the door.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-858</x>
        <y>697</y>
        <position>
          <x>-858</x>
          <y>697</y>
        </position>
        <center>
          <x>-772</x>
          <y>747</y>
        </center>
        <min>
          <x>-858</x>
          <y>697</y>
        </min>
        <max>
          <x>-686</x>
          <y>797</y>
        </max>
        <width>172</width>
        <height>100</height>
        <size>
          <x>172</x>
          <y>100</y>
        </size>
        <xMin>-858</xMin>
        <yMin>697</yMin>
        <xMax>-686</xMax>
        <yMax>797</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The shack houses a hatch leading underground.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>160</x>
                <y>65</y>
                <position>
                  <x>160</x>
                  <y>65</y>
                </position>
                <center>
                  <x>165</x>
                  <y>70</y>
                </center>
                <min>
                  <x>160</x>
                  <y>65</y>
                </min>
                <max>
                  <x>170</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>160</xMin>
                <yMin>65</yMin>
                <xMax>170</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>14</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Down the rabbit hole.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-648</x>
        <y>208</y>
        <position>
          <x>-648</x>
          <y>208</y>
        </position>
        <center>
          <x>-572.5</x>
          <y>258</y>
        </center>
        <min>
          <x>-648</x>
          <y>208</y>
        </min>
        <max>
          <x>-497</x>
          <y>308</y>
        </max>
        <width>151</width>
        <height>100</height>
        <size>
          <x>151</x>
          <y>100</y>
        </size>
        <xMin>-648</xMin>
        <yMin>208</yMin>
        <xMax>-497</xMax>
        <yMax>308</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Moments after pushing the intercom, a crackling voice emits from the intercom telling you to come inside.

Upon stepping inside, you spot a hatch leading down to the laboratory.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>65</y>
                <position>
                  <x>139</x>
                  <y>65</y>
                </position>
                <center>
                  <x>144</x>
                  <y>70</y>
                </center>
                <min>
                  <x>139</x>
                  <y>65</y>
                </min>
                <max>
                  <x>149</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>65</yMin>
                <xMax>149</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>18</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Down the hatch!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-658</x>
        <y>588</y>
        <position>
          <x>-658</x>
          <y>588</y>
        </position>
        <center>
          <x>-582.5</x>
          <y>638</y>
        </center>
        <min>
          <x>-658</x>
          <y>588</y>
        </min>
        <max>
          <x>-507</x>
          <y>688</y>
        </max>
        <width>151</width>
        <height>100</height>
        <size>
          <x>151</x>
          <y>100</y>
        </size>
        <xMin>-658</xMin>
        <yMin>588</yMin>
        <xMax>-507</xMax>
        <yMax>688</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The door gives way easily and you spot a hatch leading underground.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>65</y>
                <position>
                  <x>139</x>
                  <y>65</y>
                </position>
                <center>
                  <x>144</x>
                  <y>70</y>
                </center>
                <min>
                  <x>139</x>
                  <y>65</y>
                </min>
                <max>
                  <x>149</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>65</yMin>
                <xMax>149</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>17</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Enter the hatch.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-539</x>
        <y>722</y>
        <position>
          <x>-539</x>
          <y>722</y>
        </position>
        <center>
          <x>-390.5</x>
          <y>786.5</y>
        </center>
        <min>
          <x>-539</x>
          <y>722</y>
        </min>
        <max>
          <x>-242</x>
          <y>851</y>
        </max>
        <width>297</width>
        <height>129</height>
        <size>
          <x>297</x>
          <y>129</y>
        </size>
        <xMin>-539</xMin>
        <yMin>722</yMin>
        <xMax>-242</xMax>
        <yMax>851</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The underground laboratory is filled with stills, beakers and vials. Large quantities of presumably narcotics litter the surroundings.

In the midst of it all, you spot a bald man with a scruffy looking beard tending to the various apparatuses.

As he spots you, he mumbles something about the rudeness of entering someone's domain unannounced and approaches you.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>285</x>
                <y>65</y>
                <position>
                  <x>285</x>
                  <y>65</y>
                </position>
                <center>
                  <x>290</x>
                  <y>70</y>
                </center>
                <min>
                  <x>285</x>
                  <y>65</y>
                </min>
                <max>
                  <x>295</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>285</xMin>
                <yMin>65</yMin>
                <xMax>295</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>16</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Inquire after Multicellulose Infused Ethanol.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>285</x>
                <y>109</y>
                <position>
                  <x>285</x>
                  <y>109</y>
                </position>
                <center>
                  <x>290</x>
                  <y>114</y>
                </center>
                <min>
                  <x>285</x>
                  <y>109</y>
                </min>
                <max>
                  <x>295</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>285</xMin>
                <yMin>109</yMin>
                <xMax>295</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>15</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Shoot him through the face.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-825</x>
        <y>851</y>
        <position>
          <x>-825</x>
          <y>851</y>
        </position>
        <center>
          <x>-736</x>
          <y>901</y>
        </center>
        <min>
          <x>-825</x>
          <y>851</y>
        </min>
        <max>
          <x>-647</x>
          <y>951</y>
        </max>
        <width>178</width>
        <height>100</height>
        <size>
          <x>178</x>
          <y>100</y>
        </size>
        <xMin>-825</xMin>
        <yMin>851</yMin>
        <xMax>-647</xMax>
        <yMax>951</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>He hits the ground before having a chance to protest.

With no distractions, you can easily search the underground laboratory for any information regarding Multicellulose Infused Ethanol.
</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>166</x>
                <y>65</y>
                <position>
                  <x>166</x>
                  <y>65</y>
                </position>
                <center>
                  <x>171</x>
                  <y>70</y>
                </center>
                <min>
                  <x>166</x>
                  <y>65</y>
                </min>
                <max>
                  <x>176</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>166</xMin>
                <yMin>65</yMin>
                <xMax>176</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>6</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Search the laboratory.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>201</x>
        <y>593</y>
        <position>
          <x>201</x>
          <y>593</y>
        </position>
        <center>
          <x>298</x>
          <y>643</y>
        </center>
        <min>
          <x>201</x>
          <y>593</y>
        </min>
        <max>
          <x>395</x>
          <y>693</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>201</xMin>
        <yMin>593</yMin>
        <xMax>395</xMax>
        <yMax>693</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Multicellulose Infused Ethanol, eh? I'm afraid a backwater planet such as this one seldom has need for such a sophisticated compound.

Nevertheless, you've piqued my interest. I suppose it would be possible to synthesize such a product given the right conditions.

Sadly, my own stills are hardly suitable for the quantities you need. You'll have to acquire the hardware before I can help you further.

A particular bunch of raiders have a reputation of being little more than drunken lunatics, who supposedly cook up their own moonshine which they market as "Mendel Moonshine".

Approach them, acquire the necessary hardware, and we'll see about synthesizing your Multicellulose Infused Ethanol."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Multi_Moonshine</nodeName>
              <nodeDiscription>The chemist told you he might be able to synthesize the Multicellulose Infused Ethanol, but that his current equipment is insufficient for the quantities you need.

He told you to seek out a gang of raiders noteworthy for producing "Mendel Moonshine" and acquire the necessary hardware.</nodeDiscription>
              <pos>Random</pos>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>Very well...</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-351</x>
        <y>552</y>
        <position>
          <x>-351</x>
          <y>552</y>
        </position>
        <center>
          <x>-202.5</x>
          <y>625.5</y>
        </center>
        <min>
          <x>-351</x>
          <y>552</y>
        </min>
        <max>
          <x>-54</x>
          <y>699</y>
        </max>
        <width>297</width>
        <height>147</height>
        <size>
          <x>297</x>
          <y>147</y>
        </size>
        <xMin>-351</xMin>
        <yMin>552</yMin>
        <xMax>-54</xMax>
        <yMax>699</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The underground laboratory is filled with stills, beakers and vials. Large quantities of presumably narcotics litter the surroundings.

In the midst of it all, you spot a bald man with a scruffy looking beard tending to the various apparatuses.

As he spots you, he mumbles something about savages who would rather break property than display basic etiquette.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>285</x>
                <y>65</y>
                <position>
                  <x>285</x>
                  <y>65</y>
                </position>
                <center>
                  <x>290</x>
                  <y>70</y>
                </center>
                <min>
                  <x>285</x>
                  <y>65</y>
                </min>
                <max>
                  <x>295</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>285</xMin>
                <yMin>65</yMin>
                <xMax>295</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>20</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>285</x>
                <y>83</y>
                <position>
                  <x>285</x>
                  <y>83</y>
                </position>
                <center>
                  <x>290</x>
                  <y>88</y>
                </center>
                <min>
                  <x>285</x>
                  <y>83</y>
                </min>
                <max>
                  <x>295</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>285</xMin>
                <yMin>83</yMin>
                <xMax>295</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>2</Chance>
              <ToDialog>16</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Inquire after Multicellulose Infused Ethanol.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>285</x>
                <y>127</y>
                <position>
                  <x>285</x>
                  <y>127</y>
                </position>
                <center>
                  <x>290</x>
                  <y>132</y>
                </center>
                <min>
                  <x>285</x>
                  <y>127</y>
                </min>
                <max>
                  <x>295</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>285</xMin>
                <yMin>127</yMin>
                <xMax>295</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>15</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Shoot the chemist.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>-363</x>
        <y>311</y>
        <position>
          <x>-363</x>
          <y>311</y>
        </position>
        <center>
          <x>-214.5</x>
          <y>384.5</y>
        </center>
        <min>
          <x>-363</x>
          <y>311</y>
        </min>
        <max>
          <x>-66</x>
          <y>458</y>
        </max>
        <width>297</width>
        <height>147</height>
        <size>
          <x>297</x>
          <y>147</y>
        </size>
        <xMin>-363</xMin>
        <yMin>311</yMin>
        <xMax>-66</xMax>
        <yMax>458</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The underground laboratory is filled with stills, beakers and vials. Large quantities of presumably narcotics litter the surroundings.

In the midst of it all, you spot a bald man with a scruffy looking beard tending to the various apparatuses.

He approaches you and says: "You're the recent arrivals belonging to the spaceship, I believe? My name is Rinus Dolphin. What is it you want of a humble chemist?"</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>285</x>
                <y>65</y>
                <position>
                  <x>285</x>
                  <y>65</y>
                </position>
                <center>
                  <x>290</x>
                  <y>70</y>
                </center>
                <min>
                  <x>285</x>
                  <y>65</y>
                </min>
                <max>
                  <x>295</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>285</xMin>
                <yMin>65</yMin>
                <xMax>295</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>2</Chance>
              <ToDialog>19</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>285</x>
                <y>83</y>
                <position>
                  <x>285</x>
                  <y>83</y>
                </position>
                <center>
                  <x>290</x>
                  <y>88</y>
                </center>
                <min>
                  <x>285</x>
                  <y>83</y>
                </min>
                <max>
                  <x>295</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>285</xMin>
                <yMin>83</yMin>
                <xMax>295</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>20</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Inquire after Multicellulose Infused Ethanol.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>285</x>
                <y>127</y>
                <position>
                  <x>285</x>
                  <y>127</y>
                </position>
                <center>
                  <x>290</x>
                  <y>132</y>
                </center>
                <min>
                  <x>285</x>
                  <y>127</y>
                </min>
                <max>
                  <x>295</x>
                  <y>137</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>285</xMin>
                <yMin>127</yMin>
                <xMax>295</xMax>
                <yMax>137</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>15</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Shoot him.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>73</x>
        <y>160</y>
        <position>
          <x>73</x>
          <y>160</y>
        </position>
        <center>
          <x>169</x>
          <y>211.5</y>
        </center>
        <min>
          <x>73</x>
          <y>160</y>
        </min>
        <max>
          <x>265</x>
          <y>263</y>
        </max>
        <width>192</width>
        <height>103</height>
        <size>
          <x>192</x>
          <y>103</y>
        </size>
        <xMin>73</xMin>
        <yMin>160</yMin>
        <xMax>265</xMax>
        <yMax>263</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Multicellulose Infused Ethanol, eh? I'm afraid a backwater planet such as this one seldom has need for such a sophisticated compound.

Nevertheless, you've piqued my interest. I suppose it would be possible to synthesize it using simple moonshine and organic matter.

The problem, however, would be the time needed for the alcohol to properly absorb the organic matter. We're talking decades and I'm fairly confident you don't have that kind of time..."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>180</x>
                <y>65</y>
                <position>
                  <x>180</x>
                  <y>65</y>
                </position>
                <center>
                  <x>185</x>
                  <y>70</y>
                </center>
                <min>
                  <x>180</x>
                  <y>65</y>
                </min>
                <max>
                  <x>190</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>180</xMin>
                <yMin>65</yMin>
                <xMax>190</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>21</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>What are you proposing?</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>141</x>
        <y>369</y>
        <position>
          <x>141</x>
          <y>369</y>
        </position>
        <center>
          <x>237</x>
          <y>419</y>
        </center>
        <min>
          <x>141</x>
          <y>369</y>
        </min>
        <max>
          <x>333</x>
          <y>469</y>
        </max>
        <width>192</width>
        <height>100</height>
        <size>
          <x>192</x>
          <y>100</y>
        </size>
        <xMin>141</xMin>
        <yMin>369</yMin>
        <xMax>333</xMax>
        <yMax>469</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Multicellulose Infused Ethanol, eh? I'm afraid a backwater planet such as this one seldom has need for such a sophisticated compound.

Nevertheless, you've piqued my interest. It might be possible to synthesize it if I were to acquire some alcohol that has endured some awfully specific circumstances.

The local privateers have great affinity with the swashbuckling privateers that used to roam the seas on ancient Earth. As such, they hold the alcoholic beverage "rum" in great regard.

Rumour has it that they have great stockpiles of this particular alcohol and that they store it in wooden barrels. The combination of said organic matter and the alcohol makes for a great starting point to synthesize your required Multicellulose Infused Ethanol."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>180</x>
                <y>65</y>
                <position>
                  <x>180</x>
                  <y>65</y>
                </position>
                <center>
                  <x>185</x>
                  <y>70</y>
                </center>
                <min>
                  <x>180</x>
                  <y>65</y>
                </min>
                <max>
                  <x>190</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>180</xMin>
                <yMin>65</yMin>
                <xMax>190</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>22</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>What are you proposing?</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>344</x>
        <y>82</y>
        <position>
          <x>344</x>
          <y>82</y>
        </position>
        <center>
          <x>419.5</x>
          <y>132</y>
        </center>
        <min>
          <x>344</x>
          <y>82</y>
        </min>
        <max>
          <x>495</x>
          <y>182</y>
        </max>
        <width>151</width>
        <height>100</height>
        <size>
          <x>151</x>
          <y>100</y>
        </size>
        <xMin>344</xMin>
        <yMin>82</yMin>
        <xMax>495</xMax>
        <yMax>182</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Extremely localized time travel.

I have a friend, called Donnie, who has been experimenting with small-scale time travel. He's only been able to travel to the future, like everybody is doing all the time, but he claims that he's been able to delay the process to take longer.

Plainly speaking, it would allow the alcohol to take longer to arrive at our own future, so that it would have time to synthesize your precious Multicellulose Infused Ethanol."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>139</x>
                <y>65</y>
                <position>
                  <x>139</x>
                  <y>65</y>
                </position>
                <center>
                  <x>144</x>
                  <y>70</y>
                </center>
                <min>
                  <x>139</x>
                  <y>65</y>
                </min>
                <max>
                  <x>149</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>139</xMin>
                <yMin>65</yMin>
                <xMax>149</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>23</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Ehhrr....</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>482</x>
        <y>321</y>
        <position>
          <x>482</x>
          <y>321</y>
        </position>
        <center>
          <x>579</x>
          <y>371</y>
        </center>
        <min>
          <x>482</x>
          <y>321</y>
        </min>
        <max>
          <x>676</x>
          <y>421</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>482</xMin>
        <yMin>321</yMin>
        <xMax>676</xMax>
        <yMax>421</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"You'll need to discover the location of their stockpiles and acquire the lot of it.

I propose seeking out the privateer squad led by one "Captain Morgan", from what I understand he is often found boasting about his love for rum and therefore should know more about the presumed stockpile."
</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Multi_Morgan</nodeName>
              <nodeDiscription>Rinus Dolphin, the chemist, theorizes that ancient rum stored in wooden barrels should prove a suitable starting point to synthesize Multicellulose Infused Ethanol.

He suggested seeking out a privateer squad led by one "Captain Morgan' to find out more about the stockpiles of rum.</nodeDiscription>
              <pos>Random</pos>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>Very well...</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>594</x>
        <y>39</y>
        <position>
          <x>594</x>
          <y>39</y>
        </position>
        <center>
          <x>691</x>
          <y>89</y>
        </center>
        <min>
          <x>594</x>
          <y>39</y>
        </min>
        <max>
          <x>788</x>
          <y>139</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>594</xMin>
        <yMin>39</yMin>
        <xMax>788</xMax>
        <yMax>139</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"Don't worry about it, it sounds a lot more complicated than it is. It's not as if we're dealing with gigawatts here.

Donnie should be able to help us out, but sadly... he's been involving himself with some unsavoury types.

Last I know he's been dealing with a bunch of raiders calling themselves the "Danseals".

Go find him and bring him back here and we'll see about fixing your Multicellulose Infused Ethanol."</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_Multi_Danseals</nodeName>
              <nodeDiscription>Rinus Dolphin, the chemist, had some crazy notions to synthesize the Multicellulose Infused Ethanol, but without any other options you have no choice but to trust him.

He sent you to find and return a man called "Donnie", who has involved himself with a bunch of raiders called the "Danseals".

You should seek them out to find Donnie. </nodeDiscription>
              <pos>Random</pos>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>Very well...</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
  </Dialogs>
  <Name>Q_M_S_Multi</Name>
</Scenario>