<?xml version="1.0" encoding="utf-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <objectiveNumber>0</objectiveNumber>
  <scenarioType>Ambush</scenarioType>
  <FilePath>C:/Users/Kevin/Desktop/Convoy/ObjectiveScenarios/Q_SonicScrews_Paylater.sc</FilePath>
  <BiomeType>Road</BiomeType>
  <CombatEndDialog>1</CombatEndDialog>
  <StartDialog>0</StartDialog>
  <CurrentDialog>0</CurrentDialog>
  <ShowGUI>false</ShowGUI>
  <Dialogs>
    <Dialog>
      <GraphRect>
        <x>275</x>
        <y>271</y>
        <position>
          <x>275</x>
          <y>271</y>
        </position>
        <center>
          <x>375.5</x>
          <y>357.5</y>
        </center>
        <min>
          <x>275</x>
          <y>271</y>
        </min>
        <max>
          <x>476</x>
          <y>444</y>
        </max>
        <width>201</width>
        <height>173</height>
        <size>
          <x>201</x>
          <y>173</y>
        </size>
        <xMin>275</xMin>
        <yMin>271</yMin>
        <xMax>476</xMax>
        <yMax>444</yMax>
      </GraphRect>
      <Name>Start dialog</Name>
      <Text>You return to the T.O.R.V.A.K. Sonic Screw production facility.

"We welcome you back.

We trust you have acquired the funds to finalize our transaction?"</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="ModifyJunk">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>189</x>
                <y>65</y>
                <position>
                  <x>189</x>
                  <y>65</y>
                </position>
                <center>
                  <x>194</x>
                  <y>70</y>
                </center>
                <min>
                  <x>189</x>
                  <y>65</y>
                </min>
                <max>
                  <x>199</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>189</xMin>
                <yMin>65</yMin>
                <xMax>199</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>2</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>-250</Amount>
              <fuelAmount>0</fuelAmount>
            </ButtonAction>
          </Actions>
          <Name>Yes! [$]</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>189</x>
                <y>109</y>
                <position>
                  <x>189</x>
                  <y>109</y>
                </position>
                <center>
                  <x>194</x>
                  <y>114</y>
                </center>
                <min>
                  <x>189</x>
                  <y>109</y>
                </min>
                <max>
                  <x>199</x>
                  <y>119</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>189</xMin>
                <yMin>109</yMin>
                <xMax>199</xMax>
                <yMax>119</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>Q_SonicScrews_Paylater2</nodeName>
              <nodeDiscription>T.O.R.V.A.K. want around $250 for their Sonic Screws, you should return when you have acquired the funds... or when you want to kill them instead.</nodeDiscription>
              <pos>SameAs</pos>
              <posSameAs>Q_SonicScrews_Facility</posSameAs>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>No... be right back!</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Torvak</enemyType>
              <difficulty>7</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Actually, we'll just kill you!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>371</x>
        <y>646</y>
        <position>
          <x>371</x>
          <y>646</y>
        </position>
        <center>
          <x>466</x>
          <y>710.477539</y>
        </center>
        <min>
          <x>371</x>
          <y>646</y>
        </min>
        <max>
          <x>561</x>
          <y>774.9551</y>
        </max>
        <width>190</width>
        <height>128.955078</height>
        <size>
          <x>190</x>
          <y>128.955078</y>
        </size>
        <xMin>371</xMin>
        <yMin>646</yMin>
        <xMax>561</xMax>
        <yMax>774.9551</yMax>
      </GraphRect>
      <Name>Loot dialog</Name>
      <Text>You've defeated all the T.O.R.V.A.K. vehicles protecting their facility.

[0loot]</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>178</x>
                <y>65</y>
                <position>
                  <x>178</x>
                  <y>65</y>
                </position>
                <center>
                  <x>183</x>
                  <y>70</y>
                </center>
                <min>
                  <x>178</x>
                  <y>65</y>
                </min>
                <max>
                  <x>188</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>178</xMin>
                <yMin>65</yMin>
                <xMax>188</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>3</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Search for Sonic Screws.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>586</x>
        <y>217</y>
        <position>
          <x>586</x>
          <y>217</y>
        </position>
        <center>
          <x>661</x>
          <y>267</y>
        </center>
        <min>
          <x>586</x>
          <y>217</y>
        </min>
        <max>
          <x>736</x>
          <y>317</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>586</xMin>
        <yMin>217</yMin>
        <xMax>736</xMax>
        <yMax>317</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>"We are pleased we could come to a mutual understanding.

Prepare to receive cargo."

After a short while a transport vehicle approaches your convoy and delivers a crate filled with an ample supply of Sonic Screws.

It is easily transferred to your MCV and you prepare to head out.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddCargo">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>138</x>
                <y>65</y>
                <position>
                  <x>138</x>
                  <y>65</y>
                </position>
                <center>
                  <x>143</x>
                  <y>70</y>
                </center>
                <min>
                  <x>138</x>
                  <y>65</y>
                </min>
                <max>
                  <x>148</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>138</xMin>
                <yMin>65</yMin>
                <xMax>148</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Great!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>677</x>
        <y>540</y>
        <position>
          <x>677</x>
          <y>540</y>
        </position>
        <center>
          <x>752</x>
          <y>590</y>
        </center>
        <min>
          <x>677</x>
          <y>540</y>
        </min>
        <max>
          <x>827</x>
          <y>640</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>677</xMin>
        <yMin>540</yMin>
        <xMax>827</xMax>
        <yMax>640</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>With no remaining guards acquiring an ample supply of Sonic Screws proves easy enough.

After transferring them to your MCV, you prepare to roll out!</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddCargo">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>138</x>
                <y>65</y>
                <position>
                  <x>138</x>
                  <y>65</y>
                </position>
                <center>
                  <x>143</x>
                  <y>70</y>
                </center>
                <min>
                  <x>138</x>
                  <y>65</y>
                </min>
                <max>
                  <x>148</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>138</xMin>
                <yMin>65</yMin>
                <xMax>148</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Great</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
  </Dialogs>
  <Name>Q_SonicScrews_Paylater</Name>
</Scenario>