<?xml version="1.0" encoding="utf-8"?>
<Scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <objectiveNumber>0</objectiveNumber>
  <scenarioType>Ambush</scenarioType>
  <FilePath>C:/Users/Ryanne/Desktop/Convoy/Assets/StreamingAssets/ObjectiveScenarios/W_Plague_NodeA.sc</FilePath>
  <BiomeType>DesertRoad</BiomeType>
  <CombatEndDialog>1</CombatEndDialog>
  <StartDialog>0</StartDialog>
  <CurrentDialog>0</CurrentDialog>
  <ShowGUI>false</ShowGUI>
  <Dialogs>
    <Dialog>
      <GraphRect>
        <x>239</x>
        <y>554</y>
        <position>
          <x>239</x>
          <y>554</y>
        </position>
        <center>
          <x>353</x>
          <y>617.477539</y>
        </center>
        <min>
          <x>239</x>
          <y>554</y>
        </min>
        <max>
          <x>467</x>
          <y>680.9551</y>
        </max>
        <width>228</width>
        <height>126.955078</height>
        <size>
          <x>228</x>
          <y>126.955078</y>
        </size>
        <xMin>239</xMin>
        <yMin>554</yMin>
        <xMax>467</xMax>
        <yMax>680.9551</yMax>
      </GraphRect>
      <Name>Start dialog</Name>
      <Text>You come across the wreck of the cure courier. It looks like he was ambushed.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>216</x>
                <y>65</y>
                <position>
                  <x>216</x>
                  <y>65</y>
                </position>
                <center>
                  <x>221</x>
                  <y>70</y>
                </center>
                <min>
                  <x>216</x>
                  <y>65</y>
                </min>
                <max>
                  <x>226</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>216</xMin>
                <yMin>65</yMin>
                <xMax>226</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>3</Chance>
              <ToDialog>2</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>216</x>
                <y>83</y>
                <position>
                  <x>216</x>
                  <y>83</y>
                </position>
                <center>
                  <x>221</x>
                  <y>88</y>
                </center>
                <min>
                  <x>216</x>
                  <y>83</y>
                </min>
                <max>
                  <x>226</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>216</xMin>
                <yMin>83</yMin>
                <xMax>226</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>3</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Secure the wreck for the cure.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>295</x>
        <y>823</y>
        <position>
          <x>295</x>
          <y>823</y>
        </position>
        <center>
          <x>416</x>
          <y>873.5</y>
        </center>
        <min>
          <x>295</x>
          <y>823</y>
        </min>
        <max>
          <x>537</x>
          <y>924</y>
        </max>
        <width>242</width>
        <height>101</height>
        <size>
          <x>242</x>
          <y>101</y>
        </size>
        <xMin>295</xMin>
        <yMin>823</yMin>
        <xMax>537</xMax>
        <yMax>924</yMax>
      </GraphRect>
      <Name>Loot dialog</Name>
      <Text>The raiders have been defeated.

[0loot]

Hopefully the cure is still intact.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddLoot">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>230</x>
                <y>65</y>
                <position>
                  <x>230</x>
                  <y>65</y>
                </position>
                <center>
                  <x>235</x>
                  <y>70</y>
                </center>
                <min>
                  <x>230</x>
                  <y>65</y>
                </min>
                <max>
                  <x>240</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>230</xMin>
                <yMin>65</yMin>
                <xMax>240</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>3</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
              <Amount>0</Amount>
            </ButtonAction>
          </Actions>
          <Name>Search for the cure.</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>604</x>
        <y>437</y>
        <position>
          <x>604</x>
          <y>437</y>
        </position>
        <center>
          <x>827.5</x>
          <y>509.5</y>
        </center>
        <min>
          <x>604</x>
          <y>437</y>
        </min>
        <max>
          <x>1051</x>
          <y>582</y>
        </max>
        <width>447</width>
        <height>145</height>
        <size>
          <x>447</x>
          <y>145</y>
        </size>
        <xMin>604</xMin>
        <yMin>437</yMin>
        <xMax>1051</xMax>
        <yMax>582</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>Several raiders come out of nowhere, they were waiting for a new challenge.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>435</x>
                <y>65</y>
                <position>
                  <x>435</x>
                  <y>65</y>
                </position>
                <center>
                  <x>440</x>
                  <y>70</y>
                </center>
                <min>
                  <x>435</x>
                  <y>65</y>
                </min>
                <max>
                  <x>445</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>435</xMin>
                <yMin>65</yMin>
                <xMax>445</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>2</Chance>
              <ToDialog>4</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
            <ButtonAction xsi:type="NextDialog">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>435</x>
                <y>83</y>
                <position>
                  <x>435</x>
                  <y>83</y>
                </position>
                <center>
                  <x>440</x>
                  <y>88</y>
                </center>
                <min>
                  <x>435</x>
                  <y>83</y>
                </min>
                <max>
                  <x>445</x>
                  <y>93</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>435</xMin>
                <yMin>83</yMin>
                <xMax>445</xMax>
                <yMax>93</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>5</ToDialog>
              <Close>true</Close>
              <Enabled>true</Enabled>
            </ButtonAction>
          </Actions>
          <Name>Quickly load the cargo and outrun the warriors.</Name>
        </DialogButton>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>They'll pay for preying on the weak!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>746</x>
        <y>679</y>
        <position>
          <x>746</x>
          <y>679</y>
        </position>
        <center>
          <x>843</x>
          <y>729</y>
        </center>
        <min>
          <x>746</x>
          <y>679</y>
        </min>
        <max>
          <x>940</x>
          <y>779</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>746</xMin>
        <yMin>679</yMin>
        <xMax>940</xMax>
        <yMax>779</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>You obtain the plague cure, luckily it's undamaged.</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>W_Plague_NodeB</nodeName>
              <nodeDiscription>You have obtained the cure, time to bring it to the town of Colonya.</nodeDiscription>
              <pos>Random</pos>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>Great!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>1230</x>
        <y>520</y>
        <position>
          <x>1230</x>
          <y>520</y>
        </position>
        <center>
          <x>1305</x>
          <y>570</y>
        </center>
        <min>
          <x>1230</x>
          <y>520</y>
        </min>
        <max>
          <x>1380</x>
          <y>620</y>
        </max>
        <width>150</width>
        <height>100</height>
        <size>
          <x>150</x>
          <y>100</y>
        </size>
        <xMin>1230</xMin>
        <yMin>520</yMin>
        <xMax>1380</xMax>
        <yMax>620</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>The raiders are upon you before you have a chance to load the cargo.

You'll have to fight!</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="StartBattle">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>0</x>
                <y>0</y>
                <position>
                  <x>0</x>
                  <y>0</y>
                </position>
                <center>
                  <x>0</x>
                  <y>0</y>
                </center>
                <min>
                  <x>0</x>
                  <y>0</y>
                </min>
                <max>
                  <x>0</x>
                  <y>0</y>
                </max>
                <width>0</width>
                <height>0</height>
                <size>
                  <x>0</x>
                  <y>0</y>
                </size>
                <xMin>0</xMin>
                <yMin>0</yMin>
                <xMax>0</xMax>
                <yMax>0</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <enemyType>Raiders</enemyType>
              <difficulty>0</difficulty>
            </ButtonAction>
          </Actions>
          <Name>Ready weapons!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
    <Dialog>
      <GraphRect>
        <x>1214</x>
        <y>353</y>
        <position>
          <x>1214</x>
          <y>353</y>
        </position>
        <center>
          <x>1311</x>
          <y>403</y>
        </center>
        <min>
          <x>1214</x>
          <y>353</y>
        </min>
        <max>
          <x>1408</x>
          <y>453</y>
        </max>
        <width>194</width>
        <height>100</height>
        <size>
          <x>194</x>
          <y>100</y>
        </size>
        <xMin>1214</xMin>
        <yMin>353</yMin>
        <xMax>1408</xMax>
        <yMax>453</yMax>
      </GraphRect>
      <Name>New dialog</Name>
      <Text>You've managed to succesfully load the cargo onto your convoy and escape the raiders!</Text>
      <DialogButtons>
        <DialogButton>
          <Actions>
            <ButtonAction xsi:type="AddObjectiveNode">
              <ActionLoot>
                <Items />
                <Fuel>0</Fuel>
                <Junk>0</Junk>
              </ActionLoot>
              <ButtonRect>
                <x>182</x>
                <y>65</y>
                <position>
                  <x>182</x>
                  <y>65</y>
                </position>
                <center>
                  <x>187</x>
                  <y>70</y>
                </center>
                <min>
                  <x>182</x>
                  <y>65</y>
                </min>
                <max>
                  <x>192</x>
                  <y>75</y>
                </max>
                <width>10</width>
                <height>10</height>
                <size>
                  <x>10</x>
                  <y>10</y>
                </size>
                <xMin>182</xMin>
                <yMin>65</yMin>
                <xMax>192</xMax>
                <yMax>75</yMax>
              </ButtonRect>
              <Chance>1</Chance>
              <ToDialog>100</ToDialog>
              <Close>false</Close>
              <Enabled>true</Enabled>
              <nodeName>W_Plague_NodeB</nodeName>
              <nodeDiscription>You have obtained the cure, time to bring it to the town of Colonya.</nodeDiscription>
              <pos>Random</pos>
              <distance>0</distance>
            </ButtonAction>
          </Actions>
          <Name>Great!</Name>
        </DialogButton>
      </DialogButtons>
    </Dialog>
  </Dialogs>
  <Name>W_Plague_NodeA</Name>
</Scenario>